# Generated by Django 5.2.1 on 2026-01-18 09:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('exams', 'Examinations'), ('results', 'Results Management'), ('attendance', 'Attendance System'), ('arrival_notification', 'Arrival Notification System'), ('exam_proofreading', 'Exam Proofreading Assistant'), ('ai_question_generator', 'AI Question Generator'), ('question_bank', 'Question Bank'), ('exam_builder', 'Exam Builder'), ('sms_notifications', 'SMS Notifications'), ('fees', 'Fees & Payments'), ('timetable', 'Timetable Management')], max_length=50, unique=True)),
                ('price_per_student', models.DecimalField(decimal_places=2, help_text='Price per student in Naira', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_base_service', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Pricing',
                'verbose_name_plural': 'Service Pricing',
                'db_table': 'service_pricing',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='School/Organization name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for subdomain', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('custom_domain_verified', models.BooleanField(default=False)),
                ('domain_verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('owner_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('secondary_admin', 'Secondary Admin'), ('primary_admin', 'Primary Admin'), ('nursery_admin', 'Nursery Admin'), ('teacher', 'Teacher')], max_length=30)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenant_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_period', models.CharField(choices=[('term', 'Per Term'), ('session', 'Per Session')], default='term', max_length=20)),
                ('base_price_per_student', models.DecimalField(decimal_places=2, default=Decimal('700.00'), max_digits=10)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('services_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('base', 'Base Package'), ('service', 'Additional Service'), ('adjustment', 'Adjustment')], max_length=20)),
                ('service', models.CharField(blank=True, choices=[('exams', 'Examinations'), ('results', 'Results Management'), ('attendance', 'Attendance System'), ('arrival_notification', 'Arrival Notification System'), ('exam_proofreading', 'Exam Proofreading Assistant'), ('ai_question_generator', 'AI Question Generator'), ('question_bank', 'Question Bank'), ('exam_builder', 'Exam Builder'), ('sms_notifications', 'SMS Notifications'), ('fees', 'Fees & Payments'), ('timetable', 'Timetable Management')], max_length=50, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenant_invoice_line_items',
                'ordering': ['item_type', 'service'],
            },
        ),
        migrations.CreateModel(
            name='TenantPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('manual', 'Manual/Bank Transfer'), ('paystack', 'Paystack')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('payment_proof', models.URLField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('exams', 'Examinations'), ('results', 'Results Management'), ('attendance', 'Attendance System'), ('arrival_notification', 'Arrival Notification System'), ('exam_proofreading', 'Exam Proofreading Assistant'), ('ai_question_generator', 'AI Question Generator'), ('question_bank', 'Question Bank'), ('exam_builder', 'Exam Builder'), ('sms_notifications', 'SMS Notifications'), ('fees', 'Fees & Payments'), ('timetable', 'Timetable Management')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'tenant_services',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='tenants.tenant')),
                ('school_code', models.CharField(blank=True, max_length=20)),
                ('school_motto', models.CharField(blank=True, max_length=500)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', max_length=7)),
                ('billing_period', models.CharField(choices=[('term', 'Per Term'), ('session', 'Per Session')], default='term', max_length=20)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('allow_student_registration', models.BooleanField(default=False)),
                ('allow_parent_registration', models.BooleanField(default=False)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('student_portal_enabled', models.BooleanField(default=True)),
                ('teacher_portal_enabled', models.BooleanField(default=True)),
                ('parent_portal_enabled', models.BooleanField(default=True)),
                ('show_position_on_result', models.BooleanField(default=True)),
                ('show_class_average_on_result', models.BooleanField(default=True)),
                ('require_token_for_result', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['custom_domain'], name='tenants_custom__b86538_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'is_active'], name='tenants_status_40db9c_idx'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tenant_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_invoices', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantinvoice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_invoices', to='academics.term'),
        ),
        migrations.AddField(
            model_name='tenantinvoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='tenants.tenantinvoice'),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantpayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenantinvoice'),
        ),
        migrations.AddField(
            model_name='tenantservice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_current_session', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='current_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_current_term', to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['tenant', 'status'], name='tenant_invo_tenant__13fcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvoice',
            index=models.Index(fields=['invoice_number'], name='tenant_invo_invoice_1ed979_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantservice',
            unique_together={('tenant', 'service')},
        ),
    ]
