# Generated by Django 5.2.1 on 2026-01-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_tenant_setup_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="account_lock_duration_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="allow_profile_image_upload",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="default_user_role",
            field=models.CharField(default="student", max_length=20),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_expiration_days",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_min_length",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_require_numbers",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_require_symbols",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_require_uppercase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="password_reset_interval_days",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="profile_image_max_size_mb",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="registration_approval_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="theme",
            field=models.CharField(default="light", max_length=20),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="typography",
            field=models.CharField(default="Inter", max_length=50),
        ),
    ]
