# Generated by Django 5.2.1 on 2026-04-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="academic_year_end",
            field=models.CharField(
                default="July", help_text="Month the academic year ends", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="academic_year_start",
            field=models.CharField(
                default="September",
                help_text="Month the academic year begins",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="allow_class_overflow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_streaming",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_subject_electives",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="terms_per_year",
            field=models.PositiveIntegerField(
                default=3, help_text="Number of terms per academic year"
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="weeks_per_term",
            field=models.PositiveIntegerField(
                default=13, help_text="Average number of weeks per term"
            ),
        ),
    ]
