# Generated by Django 5.2.1 on 2026-04-09 12:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenantsettings_academic_year_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="allow_late_arrival",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="allow_subject_changes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_attendance_tracking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_credit_system",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_cross_cutting_subjects",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_grade_curving",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_grade_weighting",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="enable_subject_prerequisites",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="grading_system",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("letter", "Letter Grade"),
                    ("gpa", "GPA"),
                    ("points", "Points"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="minimum_attendance_percentage",
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="pass_percentage",
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="require_attendance",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="favicon",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="School favicon stored in Cloudinary",
                max_length=255,
                null=True,
                verbose_name="favicon",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="School logo stored in Cloudinary",
                max_length=255,
                null=True,
                verbose_name="logo",
            ),
        ),
    ]
