# Generated by Django 5.2.1 on 2026-04-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenantsettings_allow_late_arrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="animations_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="border_radius",
            field=models.CharField(
                choices=[
                    ("rounded-none", "Sharp"),
                    ("rounded", "Slightly Rounded"),
                    ("rounded-lg", "Rounded"),
                    ("rounded-xl", "More Rounded"),
                    ("rounded-2xl", "Very Rounded"),
                ],
                default="rounded-lg",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="compact_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="high_contrast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="shadow_style",
            field=models.CharField(
                choices=[
                    ("shadow-none", "No Shadow"),
                    ("shadow-sm", "Subtle Shadow"),
                    ("shadow-md", "Medium Shadow"),
                    ("shadow-lg", "Large Shadow"),
                    ("shadow-xl", "Extra Large Shadow"),
                ],
                default="shadow-md",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "Default (Recommended)"),
                    ("modern", "Modern"),
                    ("classic", "Classic"),
                    ("vibrant", "Vibrant"),
                    ("minimal", "Minimal"),
                    ("corporate", "Corporate"),
                    ("premium", "Premium"),
                    ("dark", "Dark Mode"),
                    ("obsidian", "Obsidian (Ultra Premium)"),
                    ("aurora", "Aurora (Ultra Premium)"),
                    ("midnight", "Midnight (Ultra Premium)"),
                    ("crimson", "Crimson (Ultra Premium)"),
                    ("forest", "Forest (Ultra Premium)"),
                    ("golden", "Golden (Ultra Premium)"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="typography",
            field=models.CharField(
                choices=[
                    ("Inter", "Inter (Recommended)"),
                    ("Roboto", "Roboto"),
                    ("Open Sans", "Open Sans"),
                    ("Poppins", "Poppins"),
                    ("Montserrat", "Montserrat"),
                ],
                default="Inter",
                max_length=50,
            ),
        ),
    ]
