# Generated by Django 5.2.1 on 2026-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_cloudflare_hostname_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="head_teacher_signature_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="head_teacher_signature_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL of the head teacher's digital signature",
                null=True,
                verbose_name="Head Teacher Signature URL",
            ),
        ),
    ]
