# Generated by Django 5.2.1 on 2026-05-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_add_head_teacher_signature_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="junior_secondary_use_subject_teachers",
            field=models.BooleanField(
                default=True,
                help_text="Junior Secondary classrooms use subject teachers (standard behaviour)",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="nursery_use_subject_teachers",
            field=models.BooleanField(
                default=False,
                help_text="Nursery classrooms use subject teachers instead of a single class teacher",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="primary_use_subject_teachers",
            field=models.BooleanField(
                default=False,
                help_text="Primary classrooms use subject teachers instead of a single class teacher",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="senior_secondary_use_subject_teachers",
            field=models.BooleanField(
                default=True,
                help_text="Senior Secondary classrooms use subject teachers (standard behaviour)",
            ),
        ),
    ]
