# Generated by Django 5.2.1 on 2026-06-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_add_teaching_model_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="security_features_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this tenant has opted into advanced security features",
            ),
        ),
    ]
