# Generated by Django 5.2.1 on 2026-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_tenantsettings_security_features_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="nursery_report_style",
            field=models.CharField(
                choices=[
                    (
                        "STANDARD",
                        "Standard (same format as Primary — subjects, CA/Exam, average, grade)",
                    ),
                    (
                        "DEVELOPMENTAL",
                        "Developmental (marks obtained, physical development, height/weight)",
                    ),
                ],
                default="DEVELOPMENTAL",
                help_text="Controls how Nursery term reports are scored and printed.",
                max_length=20,
            ),
        ),
    ]
