# Generated by Django 5.2.1 on 2026-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_tenantsettings_nursery_report_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="show_subject_min_max",
            field=models.BooleanField(
                default=False,
                help_text="Show 'Highest in Class' / 'Lowest in Class' columns for each subject on term reports.",
            ),
        ),
    ]
