# Generated by Django 5.2.1 on 2026-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenantsettings_show_subject_min_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="show_physical_development",
            field=models.BooleanField(
                default=True,
                help_text="Show the Physical Development / Growth Measurements section on Nursery term reports when data has been entered for a student.",
            ),
        ),
    ]
