# Generated by Django 5.2.1 on 2026-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_tenantsettings_show_physical_development"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="affective_domain_applies_to",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of EducationLevel level_type codes (e.g. ['NURSERY','PRIMARY']) for which the Affective Domain section appears, when show_affective_domain is True. Empty list ([]) = applies to ALL levels. Set explicitly to restrict to specific levels. Has no effect when show_affective_domain is False.",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="affective_domain_rating_mode",
            field=models.CharField(
                choices=[
                    ("numeric", "Numeric grid (5-4-3-2-1 tick grid) — current default"),
                    ("text", "Text label (e.g. Excellent / Very Good / Good)"),
                ],
                default="numeric",
                help_text="How the Affective Domain section is printed on term reports.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="physical_development_applies_to",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of EducationLevel level_type codes (e.g. ['NURSERY'], ['NURSERY','PRIMARY']) for which the Physical Development section appears on STANDARD-style term reports. Empty list ([]) = no levels selected — the section will not show anywhere via this setting. Does not affect Nursery reports using the DEVELOPMENTAL style, which always include physical development regardless of this setting.",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="psychomotor_applies_to",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of EducationLevel level_type codes (e.g. ['NURSERY','PRIMARY']) for which the Psychomotor Skills section appears, when show_psychomotor is True. Empty list ([]) = applies to ALL levels. Set explicitly to restrict to specific levels. Has no effect when show_psychomotor is False.",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="psychomotor_rating_mode",
            field=models.CharField(
                choices=[
                    ("numeric", "Numeric grid (5-4-3-2-1 tick grid) — current default"),
                    ("text", "Text label (e.g. Excellent / Very Good / Good)"),
                ],
                default="numeric",
                help_text="How the Psychomotor Skills section is printed on term reports.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="show_affective_domain",
            field=models.BooleanField(
                default=False,
                help_text="Master on/off switch for the Affective Domain section on term reports. If off, the section does not appear regardless of any other Affective Domain setting.",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="show_psychomotor",
            field=models.BooleanField(
                default=False,
                help_text="Master on/off switch for the Psychomotor Skills section on term reports. If off, the section does not appear regardless of any other Psychomotor setting.",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="show_physical_development",
            field=models.BooleanField(
                default=True,
                help_text="Master on/off switch for the Physical Development / Growth Measurements section on term reports.",
            ),
        ),
    ]
