# Generated by hand to match Django's migration format (no local Django
# environment available to run makemigrations in this session).
#
# 1. Tenant.referred_by - the platform user (e.g. a marketer) credited with
#    bringing a school onto the platform.
# 2. PlatformContent - singleton row holding the main marketing site's
#    editable About/Contact copy.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0014_tenantsettings_affective_domain_applies_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Platform user (e.g. marketer) credited with bringing this school onto the platform",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PlatformContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_hero_title", models.CharField(blank=True, default="", max_length=255)),
                ("about_hero_subtitle", models.TextField(blank=True, default="")),
                ("about_mission_title", models.CharField(blank=True, default="", max_length=255)),
                ("about_mission_body", models.TextField(blank=True, default="")),
                ("about_vision_title", models.CharField(blank=True, default="", max_length=255)),
                ("about_vision_body", models.TextField(blank=True, default="")),
                ("about_story_title", models.CharField(blank=True, default="", max_length=255)),
                ("about_story_body", models.TextField(blank=True, default="")),
                ("about_values", models.JSONField(blank=True, default=list)),
                ("about_stats", models.JSONField(blank=True, default=list)),
                ("contact_intro", models.TextField(blank=True, default="")),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=32)),
                ("contact_address", models.TextField(blank=True, default="")),
                ("contact_office_hours", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "platform_content",
            },
        ),
    ]
