# Generated by Django 5.2.1 on 2026-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_tenant_referred_by_platformcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcontent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
