# Generated by Django 5.2.1 on 2026-09-18 16:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_alter_platformcontent_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepricing",
            name="price_per_student_per_session",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per student for a whole session, in Naira. Blank means three times the term price.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="servicepricing",
            name="price_per_student",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price per student for one term, in Naira",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="servicepricing",
            name="service",
            field=models.CharField(
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvoicelineitem",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantservice",
            name="service",
            field=models.CharField(
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
            ),
        ),
    ]
