# Generated by Django 5.2.1 on 2026-09-18 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_price_cbt_and_gate_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantinvoice",
            name="base_price_per_student",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("800.00"),
                help_text="Basic package price per student for one term, in Naira",
                max_digits=10,
            ),
        ),
    ]
