# Generated by Django 5.2.1 on 2026-09-22 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def switch_sms_off(apps, schema_editor):
    """
    SMS was in the Basic package and is now an add-on billed per message.
    A school that switched it on while it was free has not agreed to pay for
    texts, so it is switched off; it can switch it back on. Email needs no
    step: it is on for every school unless the school switches it off.
    """
    TenantService = apps.get_model("tenants", "TenantService")
    TenantService.objects.filter(service="sms_notifications", is_enabled=True).update(
        is_enabled=False, disabled_at=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_basic_package_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepricing",
            name="service",
            field=models.CharField(
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("email_notifications", "Email Notifications"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvoicelineitem",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("email_notifications", "Email Notifications"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantservice",
            name="service",
            field=models.CharField(
                choices=[
                    ("exams", "Examinations"),
                    ("results", "Results Management"),
                    ("attendance", "Attendance System"),
                    ("arrival_notification", "Arrival Notification System"),
                    ("gate_tracker", "Gate Tracker"),
                    ("exam_proofreading", "Exam Proofreading Assistant"),
                    ("ai_question_generator", "AI Question Generator"),
                    ("question_bank", "Question Bank"),
                    ("exam_builder", "Exam Builder"),
                    ("cbt", "Computer-Based Testing (CBT)"),
                    ("email_notifications", "Email Notifications"),
                    ("sms_notifications", "SMS Notifications"),
                    ("fees", "Fees & Payments"),
                    ("timetable", "Timetable Management"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SentSms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=20)),
                ("provider", models.CharField(default="termii", max_length=20)),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms",
                        to="tenants.tenantinvoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_sms",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_sent_sms",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "invoice"],
                        name="tenant_sent_tenant__60e542_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(switch_sms_off, migrations.RunPython.noop),
    ]
