# Generated by Django 5.2.1 on 2026-09-23 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_email_notifications_and_sms_per_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_price_per_student",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basic package, per student for one term, in Naira",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "basic_price_per_student_per_session",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Basic package, per student for a whole session. Blank means three times the term price.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sms_price_per_message",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per text sent. Blank means the standard price.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="What was agreed with the school, for the record",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Pricing",
                "verbose_name_plural": "Tenant Pricing",
                "db_table": "tenant_pricing",
            },
        ),
        migrations.CreateModel(
            name="TenantAddOnPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("exams", "Examinations"),
                            ("results", "Results Management"),
                            ("attendance", "Attendance System"),
                            ("arrival_notification", "Arrival Notification System"),
                            ("gate_tracker", "Gate Tracker"),
                            ("exam_proofreading", "Exam Proofreading Assistant"),
                            ("ai_question_generator", "AI Question Generator"),
                            ("question_bank", "Question Bank"),
                            ("exam_builder", "Exam Builder"),
                            ("cbt", "Computer-Based Testing (CBT)"),
                            ("email_notifications", "Email Notifications"),
                            ("sms_notifications", "SMS Notifications"),
                            ("fees", "Fees & Payments"),
                            ("timetable", "Timetable Management"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "price_per_student",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per student for one term, in Naira",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "price_per_student_per_session",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Per student for a whole session. Blank means three terms.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_on_prices",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_add_on_price",
                "ordering": ["service"],
                "unique_together": {("tenant", "service")},
            },
        ),
    ]
