# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_academiccalendar_event_type_and_more"),
        ("tenants", "0022_arrival_needs_gate_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantinvoice",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tenant_invoices",
                to="academics.academicsession",
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvoice",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tenant_invoices",
                to="academics.term",
            ),
        ),
    ]
