# Generated by Django 5.2.1 on 2026-01-19 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculum_unique_together_and_more'),
        ('classroom', '0012_alter_classroom_unique_together_and_more'),
        ('students', '0002_resultchecktoken_and_more'),
        ('tenants', '0002_add_tenant_setup_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resultchecktoken',
            name='students_re_token_76ede9_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_educati_918345_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_is_acti_c00e81_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_st_classro_489d80_idx',
        ),
        migrations.AlterUniqueTogether(
            name='resultchecktoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultchecktoken',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='resultchecktoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Student's unique registration number", max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultchecktoken',
            unique_together={('tenant', 'student', 'school_term'), ('tenant', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('tenant', 'registration_number')},
        ),
        migrations.AddIndex(
            model_name='resultchecktoken',
            index=models.Index(fields=['tenant', 'token'], name='students_re_tenant__8b9bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'education_level', 'student_class'], name='students_st_tenant__cb7adc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'is_active'], name='students_st_tenant__77e51f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['tenant', 'classroom'], name='students_st_tenant__cc3243_idx'),
        ),
    ]
