# Generated by Django 5.2.1 on 2026-02-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_curriculum_unique_together_and_more"),
        ("classroom", "0012_alter_classroom_unique_together_and_more"),
        (
            "students",
            "0003_remove_resultchecktoken_students_re_token_76ede9_idx_and_more",
        ),
        ("teacher", "0004_alter_teacherschedule_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Primary 1', 'SS 3')",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., 'PRIMARY_1', 'SS_3')",
                        max_length=20,
                    ),
                ),
                (
                    "grade_number",
                    models.IntegerField(help_text="Grade number (1, 2, 3, etc.)"),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Overall order for sorting (0=earliest)"
                    ),
                ),
                (
                    "default_capacity",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="Default capacity for sections of this class",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about this class",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20)),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("NURSERY", "Nursery"),
                            ("PRIMARY", "Primary"),
                            ("JUNIOR_SECONDARY", "Junior Secondary"),
                            ("SENIOR_SECONDARY", "Senior Secondary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Order for sorting (0=earliest)"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Education Level",
                "verbose_name_plural": "Education Levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g., 'A', 'B', 'C', 'Gold', 'Diamond')",
                        max_length=10,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Room/classroom number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of students in this section",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["class_grade__order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": [
                    "student_class__order",
                    "section__name",
                    "user__first_name",
                ],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_tenant__cb7adc_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_tenant__cc3243_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.RemoveField(
            model_name="student",
            name="education_level",
        ),
        migrations.AlterField(
            model_name="student",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Preferred payment method",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's current class/grade",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="students.class",
            ),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this class belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="students.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic session for this section",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academics.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_grade",
            field=models.ForeignKey(
                help_text="The class this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="students.class",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary teacher for this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sections",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific section assignment (e.g., 'A', 'B')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.section",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "student_class", "section"],
                name="students_st_tenant__14b424_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "student_class"],
                name="students_st_tenant__0866a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="educationlevel",
            index=models.Index(
                fields=["tenant", "code"], name="students_ed_tenant__84587b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="educationlevel",
            index=models.Index(
                fields=["tenant", "is_active"], name="students_ed_tenant__81daa4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="educationlevel",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "education_level", "order"],
                name="students_cl_tenant__897aa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "is_active"], name="students_cl_tenant__c75199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["tenant", "code"], name="students_cl_tenant__6c4661_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["tenant", "class_grade", "is_active"],
                name="students_se_tenant__d8ebff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["tenant", "is_active"], name="students_se_tenant__504b16_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("tenant", "class_grade", "name", "academic_year")},
        ),
    ]
