# Generated by Django 5.2.1 on 2026-03-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_fk_fields_to_fee_structure"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="class",
            new_name="student_cla_tenant__3ea905_idx",
            old_name="students_cl_tenant__897aa1_idx",
        ),
        migrations.RenameIndex(
            model_name="class",
            new_name="student_cla_tenant__fc1be7_idx",
            old_name="students_cl_tenant__c75199_idx",
        ),
        migrations.RenameIndex(
            model_name="class",
            new_name="student_cla_tenant__cafcc1_idx",
            old_name="students_cl_tenant__6c4661_idx",
        ),
        migrations.RenameIndex(
            model_name="section",
            new_name="student_sec_tenant__eb6254_idx",
            old_name="students_se_tenant__d8ebff_idx",
        ),
        migrations.RenameIndex(
            model_name="section",
            new_name="student_sec_tenant__bad5e7_idx",
            old_name="students_se_tenant__504b16_idx",
        ),
    ]
