# Generated by Django 5.2.1 on 2026-03-23 17:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classroom",
            "0014_class_alter_classroom_options_alter_section_options_and_more",
        ),
        ("fee", "0006_alter_feestructure_student_class"),
        ("result", "0012_alter_resultsheet_student_class"),
        (
            "students",
            "0005_rename_students_cl_tenant__897aa1_idx_student_cla_tenant__3ea905_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="class_grade",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's current class/grade",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="classroom.class",
            ),
        ),
        migrations.RemoveField(
            model_name="section",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="section",
            name="class_teacher",
        ),
        migrations.RemoveField(
            model_name="section",
            name="tenant",
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific section assignment (e.g., 'A', 'B')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="classroom.section",
            ),
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]