# Generated by Django 5.2.1 on 2026-03-24 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0016_alter_gradelevel_options_and_more"),
        ("fee", "0007_alter_feestructure_education_level"),
        ("result", "0013_alter_scoringconfiguration_options_and_more"),
        ("students", "0006_remove_section_class_grade_and_more"),
        ("tenants", "0003_add_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_ext", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("imported_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Upload Record",
                "verbose_name_plural": "Bulk Upload Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="EducationLevel",
        ),
        migrations.AddIndex(
            model_name="bulkuploadrecord",
            index=models.Index(
                fields=["tenant", "status"], name="students_bu_tenant__c11373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkuploadrecord",
            index=models.Index(
                fields=["tenant", "uploaded_by"], name="students_bu_tenant__19cdb9_idx"
            ),
        ),
    ]
