# Generated by Django 5.2.1 on 2026-04-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_bulkuploadrecord_delete_educationlevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="lga_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="lga_of_residence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="state_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year_admitted",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
