# Generated by Django 5.2.1 on 2026-04-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_student_lga_of_origin_student_lga_of_residence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkuploadrecord",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_bulk_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
