# Generated by Django 5.2.1 on 2026-05-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_bulkuploadrecord_uploaded_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkuploadrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Student Bulk Upload Record",
                "verbose_name_plural": "Student Bulk Upload Records",
            },
        ),
        migrations.AlterField(
            model_name="resultchecktoken",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_tokens",
                to="students.student",
            ),
        ),
    ]
