# Generated by Django 5.2.1 on 2026-05-28 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_alter_bulkuploadrecord_options_and_more"),
        ("tenants", "0009_add_teaching_model_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("tenant", "registration_number"), ("tenant", "user")},
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
