# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom",
            "0023_alter_class_education_level_alter_stream_grade_level_and_more",
        ),
        ("students", "0011_alter_student_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's current class/grade",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students",
                to="classroom.class",
            ),
        ),
    ]
