# Generated by Django 5.2.1 on 2026-01-17 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0011_alter_classroomteacherassignment_classroom_and_more"),
        ("lesson", "0001_initial"),
        ("subject", "0001_initial"),
        ("teacher", "0003_teacher_signature_uploaded_at_teacher_signature_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "date", "status"],
                name="lesson_less_teacher_158c4e_idx",
            ),
        ),
    ]
