# Generated by Django 5.2.1 on 2026-03-03 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_alter_term_options_calendareventtype_and_more"),
        ("classroom", "0013_add_new_category_and_type_models"),
        ("students", "0004_add_fk_fields_to_fee_structure"),
        ("subject", "0003_add_new_category_and_type_models"),
        ("teacher", "0004_alter_teacherschedule_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Difficulty level name (e.g., 'Easy', 'Medium', 'Hard')",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., 'easy', 'medium', 'hard')",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display (e.g., '#4CAF50' for easy)",
                        max_length=7,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_difficulty_level",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("pass_marks", models.PositiveIntegerField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=100)),
                ("max_students", models.PositiveIntegerField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                ("materials_allowed", models.TextField(blank=True)),
                ("materials_provided", models.TextField(blank=True)),
                ("objective_questions", models.JSONField(blank=True, default=list)),
                ("theory_questions", models.JSONField(blank=True, default=list)),
                ("practical_questions", models.JSONField(blank=True, default=list)),
                ("custom_sections", models.JSONField(blank=True, default=list)),
                ("objective_instructions", models.TextField(blank=True)),
                ("theory_instructions", models.TextField(blank=True)),
                ("practical_instructions", models.TextField(blank=True)),
                (
                    "questions_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exam_questions/"
                    ),
                ),
                (
                    "answer_key",
                    models.FileField(blank=True, null=True, upload_to="exam_answers/"),
                ),
                ("is_practical", models.BooleanField(default=False)),
                ("requires_computer", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval_notes",
                    models.TextField(blank=True, help_text="Notes from the approver"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection if applicable"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Teacher who approved this exam",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_exams",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "difficulty_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Difficulty level of the exam",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="exam.difficultylevel",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "invigilators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invigilated_exams",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classroom.section",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stream for Senior Secondary exams (Science, Arts, Commercial, Technical)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="classroom.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam",
                "ordering": ["exam_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("is_registered", models.BooleanField(default=True)),
                ("is_present", models.BooleanField(default=False)),
                ("has_special_needs", models.BooleanField(default=False)),
                ("special_needs_description", models.TextField(blank=True)),
                ("extra_time_minutes", models.PositiveIntegerField(default=0)),
                ("seat_number", models.CharField(blank=True, max_length=10)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exams_registration",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExamReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission_note",
                    models.TextField(blank=True, help_text="Note to reviewers"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="exam.exam",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "question_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Which question this comment relates to (0-indexed)",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Which section: objective, theory, practical, custom",
                        max_length=50,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="exam.examreview",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_review_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("request_changes", "Request Changes"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewers",
                        to="exam.examreview",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_reviewer",
                "ordering": ["assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_start", models.DateTimeField(blank=True, null=True)),
                ("registration_end", models.DateTimeField(blank=True, null=True)),
                ("results_publication_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_late_registration", models.BooleanField(default=False)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this as the default exam schedule for new exams",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.academicsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.term"
                    ),
                ),
            ],
            options={
                "db_table": "exams_schedule",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Exam schedule this exam belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="exam.examschedule",
            ),
        ),
        migrations.CreateModel(
            name="ExamStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_registered", models.PositiveIntegerField(default=0)),
                ("total_appeared", models.PositiveIntegerField(default=0)),
                ("total_absent", models.PositiveIntegerField(default=0)),
                (
                    "highest_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "lowest_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "median_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("grade_a_count", models.PositiveIntegerField(default=0)),
                ("grade_b_count", models.PositiveIntegerField(default=0)),
                ("grade_c_count", models.PositiveIntegerField(default=0)),
                ("grade_d_count", models.PositiveIntegerField(default=0)),
                ("grade_e_count", models.PositiveIntegerField(default=0)),
                ("grade_f_count", models.PositiveIntegerField(default=0)),
                ("total_passed", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                (
                    "pass_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="exam.exam",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exams_statistics",
            },
        ),
        migrations.CreateModel(
            name="ExamStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Status name (e.g., 'Draft', 'Pending Approval', 'Approved')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., 'draft', 'pending_approval', 'approved')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the initial status for new exams?",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False, help_text="Is this a final/terminal status?"
                    ),
                ),
                (
                    "allows_editing",
                    models.BooleanField(
                        default=True, help_text="Can exam be edited in this status?"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_status",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.ForeignKey(
                help_text="Current status of the exam",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="exam.examstatus",
            ),
        ),
        migrations.CreateModel(
            name="ExamTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "structure",
                    models.JSONField(
                        help_text="Template structure with sections, question counts, marks allocation"
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=100)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "default_instructions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default instructions for general, objective, theory, practical sections",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Make available to all teachers in the school",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher/Admin who created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional - leave blank for generic templates",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subject.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Exam type name (e.g., 'Quiz', 'Mid-Term Examination')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., 'quiz', 'mid_term', 'final_exam')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default weight percentage in overall grade",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying exam types"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                help_text="Type of exam (Quiz, Test, Mid-Term, Final, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="exam.examtype",
            ),
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("objective", "Objective"),
                            ("theory", "Theory"),
                            ("practical", "Practical"),
                        ],
                        default="objective",
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="HTML content from RichTextEditor"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of options for objective questions",
                    ),
                ),
                ("correct_answer", models.CharField(blank=True, max_length=255)),
                (
                    "answer_guideline",
                    models.TextField(
                        blank=True, help_text="Expected answer or marking guide"
                    ),
                ),
                (
                    "expected_points",
                    models.TextField(
                        blank=True, help_text="Key points for theory questions"
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("subtopic", models.CharField(blank=True, max_length=200)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Make available to other teachers in the school",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                (
                    "table_data",
                    models.TextField(blank=True, help_text="Table HTML or JSON"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher who created this question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        help_text="Difficulty level of this question",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="exam.difficultylevel",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_question_bank",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_initial", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
                ("color_code", models.CharField(blank=True, max_length=7)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_review_status",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="examreview",
            name="status",
            field=models.ForeignKey(
                help_text="Current review status",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="exam.reviewstatus",
            ),
        ),
        migrations.AddIndex(
            model_name="difficultylevel",
            index=models.Index(
                fields=["tenant", "code"], name="exam_diffic_tenant__467f8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="difficultylevel",
            index=models.Index(
                fields=["tenant", "is_active"], name="exam_diffic_tenant__f966c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="difficultylevel",
            unique_together={("tenant", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="examregistration",
            unique_together={("tenant", "exam", "student")},
        ),
        migrations.AddIndex(
            model_name="examreviewcomment",
            index=models.Index(
                fields=["tenant", "review", "-created_at"],
                name="exam_review_tenant__b232ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examreviewer",
            unique_together={("tenant", "review", "reviewer")},
        ),
        migrations.AlterUniqueTogether(
            name="examschedule",
            unique_together={("tenant", "academic_session", "term", "name")},
        ),
        migrations.AddIndex(
            model_name="examstatus",
            index=models.Index(
                fields=["tenant", "code"], name="exam_status_tenant__781439_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examstatus",
            index=models.Index(
                fields=["tenant", "is_active"], name="exam_status_tenant__d3422a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examstatus",
            index=models.Index(
                fields=["tenant", "is_initial"], name="exam_status_tenant__cd7e24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examstatus",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="examtemplate",
            index=models.Index(
                fields=["tenant", "grade_level"], name="exam_templa_tenant__1c6d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examtemplate",
            index=models.Index(
                fields=["tenant", "is_shared"], name="exam_templa_tenant__91d9e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examtemplate",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="examtype",
            index=models.Index(
                fields=["tenant", "code"], name="exam_type_tenant__e9a21a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examtype",
            index=models.Index(
                fields=["tenant", "is_active"], name="exam_type_tenant__90ecc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examtype",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["tenant", "exam_type"], name="exams_exam_tenant__144b49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["tenant", "status"], name="exams_exam_tenant__abb1bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["tenant", "exam_date"], name="exams_exam_tenant__fd1afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["tenant", "grade_level"], name="exams_exam_tenant__ffc0d5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "subject", "difficulty"],
                name="exam_questi_tenant__27664f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "created_by", "-created_at"],
                name="exam_questi_tenant__91a4b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "is_shared"], name="exam_questi_tenant__95c809_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewstatus",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="examreview",
            index=models.Index(
                fields=["tenant", "status"], name="exam_review_tenant__f2ac0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examreview",
            index=models.Index(
                fields=["tenant", "submitted_by", "-created_at"],
                name="exam_review_tenant__a1d01c_idx",
            ),
        ),
    ]
