# Generated by Django 5.2.1 on 2026-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="print_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-exam print formatting: font_family, font_size, line_height, option_layout (auto|inline|stacked), column_layout (1|2), margin (normal|narrow|wide), show_marks, show_instructions.",
            ),
        ),
    ]
