# Generated by Django 5.2.1 on 2026-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_add_print_settings_to_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbank",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("single", "Choose one"),
                    ("multiple", "Choose all that apply"),
                    ("true_false", "True or false"),
                    ("numeric", "Number"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="partial_credit",
            field=models.BooleanField(
                default=False,
                help_text="For choose all that apply: marks for part of the right choices",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="tolerance",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="How far either side of a numeric answer still counts",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Shown beside a numeric answer box, e.g. cm",
                max_length=30,
            ),
        ),
    ]
