# Generated by Django 5.2.1 on 2026-01-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculum_unique_together_and_more'),
        ('exam', '0002_alter_exam_code'),
        ('students', '0002_resultchecktoken_and_more'),
        ('tenants', '0002_add_tenant_setup_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='examstatistics',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examregistration',
            unique_together={('tenant', 'exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('tenant', 'academic_session', 'term', 'name')},
        ),
    ]
