# Generated by Django 5.2.1 on 2026-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_question_bank_answer_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="section_audio",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='A sound clip for the objective or theory section, played on the CBT paper: {"objective": {"url", "title", "plays", "duration"}}. A custom section keeps its own under "audio".',
            ),
        ),
    ]
