# Generated by Django 5.2.1 on 2026-01-22 21:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0012_alter_classroom_unique_together_and_more"),
        ("exam", "0003_alter_examregistration_unique_together_and_more"),
        ("subject", "0002_add_tenant_fields"),
        ("teacher", "0004_alter_teacherschedule_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("in_review", "In Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission_note",
                    models.TextField(blank=True, help_text="Note to reviewers"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="exam.exam",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "question_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Which question this comment relates to (0-indexed)",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Which section: objective, theory, practical, custom",
                        max_length=50,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="exam.examreview",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_review_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("request_changes", "Request Changes"),
                            ("reject", "Reject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewers",
                        to="exam.examreview",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_reviews",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_reviewer",
                "ordering": ["assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "structure",
                    models.JSONField(
                        help_text="Template structure with sections, question counts, marks allocation"
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=100)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "default_instructions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default instructions for general, objective, theory, practical sections",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Make available to all teachers in the school",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher/Admin who created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional - leave blank for generic templates",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subject.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("objective", "Objective"),
                            ("theory", "Theory"),
                            ("practical", "Practical"),
                        ],
                        default="objective",
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="HTML content from RichTextEditor"),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of options for objective questions",
                    ),
                ),
                ("correct_answer", models.CharField(blank=True, max_length=255)),
                (
                    "answer_guideline",
                    models.TextField(
                        blank=True, help_text="Expected answer or marking guide"
                    ),
                ),
                (
                    "expected_points",
                    models.TextField(
                        blank=True, help_text="Key points for theory questions"
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("subtopic", models.CharField(blank=True, max_length=200)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                            ("mixed", "Mixed"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="Make available to other teachers in the school",
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                (
                    "table_data",
                    models.TextField(blank=True, help_text="Table HTML or JSON"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Teacher who created this question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exam_question_bank",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="examreview",
            index=models.Index(
                fields=["tenant", "status"], name="exam_review_tenant__c2f865_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examreview",
            index=models.Index(
                fields=["tenant", "submitted_by", "-created_at"],
                name="exam_review_tenant__a1d01c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examreviewcomment",
            index=models.Index(
                fields=["tenant", "review", "-created_at"],
                name="exam_review_tenant__b232ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examreviewer",
            unique_together={("tenant", "review", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="examtemplate",
            index=models.Index(
                fields=["tenant", "grade_level"], name="exam_templa_tenant__1c6d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examtemplate",
            index=models.Index(
                fields=["tenant", "is_shared"], name="exam_templa_tenant__91d9e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examtemplate",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "subject", "difficulty"],
                name="exam_questi_tenant__935115_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "created_by", "-created_at"],
                name="exam_questi_tenant__91a4b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["tenant", "is_shared"], name="exam_questi_tenant__95c809_idx"
            ),
        ),
    ]
