# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_exam_plain_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="difficulty_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Difficulty level of the exam",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="exams",
                to="exam.difficultylevel",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                help_text="Type of exam (Quiz, Test, Mid-Term, Final, etc.)",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="exams",
                to="exam.examtype",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.ForeignKey(
                help_text="Current status of the exam",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="exams",
                to="exam.examstatus",
            ),
        ),
        migrations.AlterField(
            model_name="examreview",
            name="status",
            field=models.ForeignKey(
                help_text="Current review status",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="reviews",
                to="exam.reviewstatus",
            ),
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="difficulty",
            field=models.ForeignKey(
                help_text="Difficulty level of this question",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions",
                to="exam.difficultylevel",
            ),
        ),
    ]
