# Generated by Django 5.2.1 on 2026-01-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0004_alter_teacherschedule_unique_together_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='curriculumsubject',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='term',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('tenant', 'name', 'education_level', 'academic_session')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumsubject',
            unique_together={('tenant', 'curriculum', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectallocation',
            unique_together={('tenant', 'subject', 'teacher', 'academic_session', 'education_level', 'student_class')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('tenant', 'academic_session', 'name')},
        ),
    ]
