# Generated by Django 5.2.1 on 2026-03-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_curriculum_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="term",
            options={
                "ordering": ["academic_session", "term_type__display_order"],
                "verbose_name": "Academic Term",
                "verbose_name_plural": "Academic Terms",
            },
        ),
        migrations.CreateModel(
            name="CalendarEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g. 'Term Start', 'Holiday')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g. 'term_start', 'holiday', 'exam')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color for calendar UI (e.g. '#4CAF50')",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon identifier for the UI",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "academics_calendar_event_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="academiccalendar",
            name="event_type",
            field=models.ForeignKey(
                help_text="Type of calendar event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendar_events",
                to="academics.calendareventtype",
            ),
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g. 'Primary', 'Junior Secondary')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g. 'nursery', 'primary', 'junior_secondary')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "academics_education_level",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this curriculum is designed for",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curricula",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="subjectallocation",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this allocation belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_allocations",
                to="academics.educationlevel",
            ),
        ),
        migrations.CreateModel(
            name="TermType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g. 'First Term', 'Semester 1')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g. 'first', 'second', 'third')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which terms appear (1 = first, 2 = second, …)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "academics_term_type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="term",
            name="term_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.termtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("tenant", "academic_session", "term_type")},
        ),
        migrations.AddIndex(
            model_name="calendareventtype",
            index=models.Index(
                fields=["tenant", "code"], name="academics_c_tenant__3d61a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendareventtype",
            index=models.Index(
                fields=["tenant", "is_active"], name="academics_c_tenant__cf421c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendareventtype",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="educationlevel",
            index=models.Index(
                fields=["tenant", "code"], name="academics_e_tenant__daba95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="educationlevel",
            index=models.Index(
                fields=["tenant", "is_active"], name="academics_e_tenant__db65b0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="educationlevel",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="termtype",
            index=models.Index(
                fields=["tenant", "code"], name="academics_t_tenant__79c412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termtype",
            index=models.Index(
                fields=["tenant", "is_active"], name="academics_t_tenant__25aecb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termtype",
            unique_together={("tenant", "code")},
        ),
        migrations.RemoveField(
            model_name="term",
            name="name",
        ),
    ]
