# Generated by Django 5.2.1 on 2026-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_term_options_calendareventtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationlevel",
            name="is_system_default",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this was auto-created as a default",
            ),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="level_type",
            field=models.CharField(
                blank=True,
                help_text="Optional category (e.g. NURSERY, PRIMARY, JSS, SSS)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="code",
            field=models.CharField(
                help_text="Unique identifier per tenant (e.g. 'primary', 'jss')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of this education level"
            ),
        ),
        migrations.AlterField(
            model_name="educationlevel",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Controls ordering (lower comes first)"
            ),
        ),
    ]
