# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academiccalendar",
            name="event_type",
            field=models.ForeignKey(
                help_text="Type of calendar event",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="calendar_events",
                to="academics.calendareventtype",
            ),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this curriculum is designed for",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="curricula",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="subjectallocation",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this allocation belongs to",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subject_allocations",
                to="academics.educationlevel",
            ),
        ),
    ]
