# Generated by Django 5.2.1 on 2026-01-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculum_unique_together_and_more'),
        ('classroom', '0011_alter_classroomteacherassignment_classroom_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='classroomteacherassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stream',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('tenant', 'section', 'academic_session', 'term', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='gradelevel',
            unique_together={('tenant', 'education_level', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('tenant', 'grade_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('tenant', 'code')},
        ),
    ]
