# Generated by Django 5.2.1 on 2026-02-27 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_curriculum_unique_together_and_more"),
        ("classroom", "0012_alter_classroom_unique_together_and_more"),
        ("students", "0004_add_fk_fields_to_fee_structure"),
        ("subject", "0002_add_tenant_fields"),
        ("teacher", "0004_alter_teacherschedule_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stream type name (e.g., 'Science', 'Arts', 'Commercial')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this stream type (e.g., 'SCIENCE', 'ARTS')",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this stream type and its focus areas",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display (e.g., '#4CAF50')",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying stream types"
                    ),
                ),
                (
                    "requires_entrance_exam",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this stream requires an entrance exam",
                    ),
                ),
                (
                    "min_grade_requirement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum grade percentage required to join this stream",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stream Type",
                "verbose_name_plural": "Stream Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="stream",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="classroom",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                help_text="Stream for Senior Secondary classrooms",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="classroom.stream",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic session for this stream",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="academics.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level this stream is for",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="streams",
                to="classroom.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Maximum number of students in this stream",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="stream_coordinator",
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher coordinating this stream",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_streams",
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_type",
            field=models.CharField(
                choices=[
                    ("SCIENCE", "Science"),
                    ("ARTS", "Arts"),
                    ("COMMERCIAL", "Commercial"),
                    ("TECHNICAL", "Technical"),
                ],
                help_text="Stream type (DEPRECATED - use stream_type_new)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["tenant", "section"], name="classroom_c_tenant__dd261f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["tenant", "academic_session", "term"],
                name="classroom_c_tenant__a2cd5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["tenant", "stream"], name="classroom_c_tenant__c2b336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_c_tenant__03d8f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroomteacherassignment",
            index=models.Index(
                fields=["tenant", "classroom"], name="classroom_c_tenant__a3e5c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroomteacherassignment",
            index=models.Index(
                fields=["tenant", "teacher"], name="classroom_c_tenant__463168_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroomteacherassignment",
            index=models.Index(
                fields=["tenant", "subject"], name="classroom_c_tenant__4afdf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["tenant", "classroom"], name="classroom_c_tenant__cf7429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["tenant", "teacher"], name="classroom_c_tenant__979ba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["day_of_week", "start_time"],
                name="classroom_c_day_of__c631b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(
                fields=["tenant", "education_level"],
                name="classroom_g_tenant__ff98e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_g_tenant__d13751_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["tenant", "grade_level"], name="classroom_s_tenant__8955ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_s_tenant__289292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["tenant", "student"], name="classroom_s_tenant__b6017a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["tenant", "classroom"], name="classroom_s_tenant__39a8fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_s_tenant__6ce893_idx"
            ),
        ),
        migrations.AddField(
            model_name="streamtype",
            name="applicable_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Education levels where this stream type is available",
                related_name="stream_types",
                to="classroom.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="streamtype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="stream_type_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of stream (new FK field)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="streams_new",
                to="classroom.streamtype",
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["tenant", "code"], name="classroom_s_tenant__f0b9e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_s_tenant__413156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamtype",
            index=models.Index(
                fields=["tenant", "code"], name="classroom_s_tenant__4770c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamtype",
            index=models.Index(
                fields=["tenant", "is_active"], name="classroom_s_tenant__841a1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamtype",
            unique_together={("tenant", "code")},
        ),
    ]
