# Generated by Django 5.2.1 on 2026-03-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_term_options_calendareventtype_and_more"),
        ("classroom", "0013_add_new_category_and_type_models"),
        (
            "students",
            "0005_rename_students_cl_tenant__897aa1_idx_student_cla_tenant__3ea905_idx_and_more",
        ),
        ("teacher", "0004_alter_teacherschedule_unique_together_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Primary 1', 'SS 3')",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code (e.g., 'PRIMARY_1', 'SS_3')",
                        max_length=20,
                    ),
                ),
                (
                    "grade_number",
                    models.IntegerField(help_text="Grade number (1, 2, 3, etc.)"),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Overall order for sorting (0=earliest)"
                    ),
                ),
                (
                    "default_capacity",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="Default capacity for sections of this class",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about this class",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "student_class",
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="classroom",
            options={
                "ordering": [
                    "section__class_grade",
                    "section__name",
                    "academic_session",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["class_grade__order", "name"],
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.RemoveIndex(
            model_name="section",
            name="classroom_s_tenant__8955ae_idx",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="section",
                    new_name="student_sec_tenant__bad5e7_idx",
                    old_name="classroom_s_tenant__289292_idx",
                ),
            ],
        ),
        migrations.AddField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic session for this section",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academics.academicsession",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of students in this section",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary teacher for this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sections",
                to="teacher.teacher",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="room_number",
            field=models.CharField(
                blank=True, help_text="Room/classroom number", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                help_text="Section name (e.g., 'A', 'B', 'C', 'Gold', 'Diamond')",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="section",
            table="student_section",
        ),
        migrations.AddField(
            model_name="class",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this class belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="students.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="class_grade",
            field=models.ForeignKey(
                blank=True,
                help_text="The class this section belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="classroom.class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("tenant", "class_grade", "name", "academic_year")},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="section",
                    index=models.Index(
                        fields=["tenant", "class_grade", "is_active"],
                        name="student_sec_tenant__eb6254_idx",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="class",
                    index=models.Index(
                        fields=["tenant", "education_level", "order"],
                        name="student_cla_tenant__3ea905_idx",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="class",
                    index=models.Index(
                        fields=["tenant", "is_active"],
                        name="student_cla_tenant__fc1be7_idx",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="class",
                    index=models.Index(
                        fields=["tenant", "code"],
                        name="student_cla_tenant__cafcc1_idx",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("tenant", "code")},
        ),
        migrations.RemoveField(
            model_name="section",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="section",
            name="grade_level",
        ),
        migrations.RemoveField(
            model_name="section",
            name="updated_at",
        ),
    ]