# Generated by Django 5.2.1 on 2026-03-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom",
            "0014_class_alter_classroom_options_alter_section_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gradelevel",
            new_name="classroom_g_tenant__837e50_idx",
            old_name="classroom_g_tenant__ff98e4_idx",
        ),
        migrations.RenameIndex(
            model_name="gradelevel",
            new_name="classroom_g_tenant__b3c8fd_idx",
            old_name="classroom_g_tenant__d13751_idx",
        ),
        migrations.AlterModelTable(
            name="gradelevel",
            table="classroom_gradelevel",
        ),
    ]
