# Generated by Django 5.2.1 on 2026-03-24 11:35
import django.db.models.deletion
from django.db import migrations, models


def populate_education_level_fks(apps, schema_editor):
    db = schema_editor.connection.alias
    EducationLevel = apps.get_model('academics', 'EducationLevel')

    level_map = {}
    for el in EducationLevel.objects.using(db).all():
        if el.level_type:
            level_map[el.level_type.upper()] = el.pk
        if el.code:
            level_map[el.code.upper()] = el.pk

    with schema_editor.connection.cursor() as cursor:
        # GradeLevel only — classroom_classroom has no education_level column
        cursor.execute("SELECT id, education_level FROM classroom_gradelevel")
        for row_id, raw_value in cursor.fetchall():
            if isinstance(raw_value, str):
                pk = level_map.get(raw_value.upper())
                if pk is None:
                    raise ValueError(
                        f"GradeLevel id={row_id}: no EducationLevel found for "
                        f"'{raw_value}'. Available: {sorted(level_map)}"
                    )
                cursor.execute(
                    "UPDATE classroom_gradelevel SET education_level = %s WHERE id = %s",
                    [pk, row_id],
                )


def reverse_populate(apps, schema_editor):
    pass  # not reversible


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
        ("classroom", "0015_fix_gradelevel_table_typo"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradelevel",
            options={
                "ordering": ["education_level", "order", "name"],
                "verbose_name": "Grade Level",
                "verbose_name_plural": "Grade Levels",
            },
        ),
        migrations.RenameIndex(
            model_name="gradelevel",
            new_name="classroom_g_tenant__9fdac4_idx",
            old_name="classroom_g_tenant__837e50_idx",
        ),
        migrations.AlterUniqueTogether(
            name="gradelevel",
            unique_together={("tenant", "education_level", "order")},
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="is_system_default",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this was auto-created as a default",
            ),
        ),

        # ✅ Populate integer PKs BEFORE Django tries to alter the column types
        migrations.RunPython(populate_education_level_fks, reverse_populate),

        migrations.AddField(
            model_name="class",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this class belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academics.educationlevel",
                null=True,   # allow null initially; tighten later once data is populated
            ),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="education_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_levels",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="gradelevel",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Order within the education level (e.g., 1 for first grade)"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradelevel",
            unique_together={
                ("tenant", "education_level", "name"),
                ("tenant", "education_level", "order"),
            },
        ),
    ]