# Generated by Django 5.2.1 on 2026-03-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
        ("classroom", "0016_alter_gradelevel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="education_level",
            field=models.ForeignKey(
                default=1,
                help_text="Education level this class belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="academics.educationlevel",
            ),
            preserve_default=False,
        ),
    ]
