# Generated by Django 5.2.1 on 2026-04-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0017_alter_class_education_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="The grade level this class maps to (e.g., Primary 1 → Grade 1)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="classroom.gradelevel",
            ),
        ),
    ]
