# Generated by Django 5.2.1 on 2026-04-06 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0018_class_grade_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific grade level this class maps to (e.g., Primary 1 → Grade 1)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="classroom.gradelevel",
            ),
        ),
    ]
