# Generated by Django 5.2.1 on 2026-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0019_alter_class_grade_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stream",
            name="stream_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SCIENCE", "Science"),
                    ("ARTS", "Arts"),
                    ("COMMERCIAL", "Commercial"),
                    ("TECHNICAL", "Technical"),
                ],
                default="",
                help_text="Stream type (DEPRECATED - use stream_type_new)",
                max_length=20,
            ),
        ),
    ]
