# Generated by Django 5.2.1 on 2026-04-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0021_alter_section_name_max_length"),
        ("teacher", "0005_bulkuploadrecord"),
        ("tenants", "0007_tenant_cloudflare_hostname_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomCoTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_teacher_assignments",
                        to="classroom.classroom",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="co_teaching_assignments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["classroom", "teacher"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "classroom"],
                        name="classroom_c_tenant__c36c54_idx",
                    ),
                    models.Index(
                        fields=["tenant", "teacher"],
                        name="classroom_c_tenant__d6d8fd_idx",
                    ),
                ],
                "unique_together": {("classroom", "teacher")},
            },
        ),
    ]
