# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_academiccalendar_event_type_and_more"),
        ("classroom", "0022_add_classroom_co_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this class belongs to",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="classes",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level this stream is for",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="streams",
                to="classroom.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="stream_type_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of stream (new FK field)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="streams_new",
                to="classroom.streamtype",
            ),
        ),
    ]
