# Generated by Django 5.2.1 on 2026-01-19 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_curriculum_unique_together_and_more'),
        ('fee', '0001_initial'),
        ('students', '0002_resultchecktoken_and_more'),
        ('tenants', '0002_add_tenant_setup_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='fee_payment_gateway_c4a309_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fee_payment_payment_fd753a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fee_payment_student_0df3a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhook',
            name='fee_payment_gateway_ba972a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentwebhook',
            name='fee_payment_process_d89412_idx',
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paymentwebhook',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentdiscount',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual Payment')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('tenant', 'receipt_number'), ('tenant', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('tenant', 'gateway')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together={('tenant', 'payment_plan', 'installment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscount',
            unique_together={('tenant', 'student', 'discount', 'academic_session')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('tenant', 'student', 'fee_structure', 'academic_session', 'term')},
        ),
        migrations.AddIndex(
            model_name='feediscount',
            index=models.Index(fields=['tenant', 'is_active'], name='fee_feedisc_tenant__66e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['tenant', 'fee_type'], name='fee_feestru_tenant__9dd3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['tenant', 'education_level'], name='fee_feestru_tenant__e8bd84_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'gateway_reference'], name='fee_payment_tenant__1cce76_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_gateway', 'gateway_status'], name='fee_payment_tenant__4ce4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'student_fee', 'verified'], name='fee_payment_tenant__faefd3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['tenant', 'gateway', 'status'], name='fee_payment_tenant__09de64_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=models.Index(fields=['tenant', 'is_active'], name='fee_payment_tenant__574426_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['tenant', 'is_paid'], name='fee_payment_tenant__32f71a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['tenant', 'is_active'], name='fee_payment_tenant__a60b99_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreminder',
            index=models.Index(fields=['tenant', 'is_sent'], name='fee_payment_tenant__837b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['tenant', 'gateway', 'event_type'], name='fee_payment_tenant__91fae2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['tenant', 'processed', 'created_at'], name='fee_payment_tenant__26c56e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdiscount',
            index=models.Index(fields=['tenant', 'student'], name='fee_student_tenant__b71528_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'student'], name='fee_student_tenant__152285_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['tenant', 'status'], name='fee_student_tenant__8bad4f_idx'),
        ),
    ]
