# Generated by Django 5.2.1 on 2026-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fee", "0002_remove_payment_fee_payment_gateway_c4a309_idx_and_more"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentinstallment",
            options={
                "ordering": ["installment_number"],
                "verbose_name": "Payment Installment",
                "verbose_name_plural": "Payment Installments",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment Plan",
                "verbose_name_plural": "Payment Plans",
            },
        ),
        migrations.RenameIndex(
            model_name="feediscount",
            new_name="fee_fee_dis_tenant__5b5f63_idx",
            old_name="fee_feedisc_tenant__66e39b_idx",
        ),
        migrations.RenameIndex(
            model_name="feestructure",
            new_name="fee_fee_str_tenant__3960c6_idx",
            old_name="fee_feestru_tenant__9dd3ef_idx",
        ),
        migrations.RenameIndex(
            model_name="feestructure",
            new_name="fee_fee_str_tenant__ecae5c_idx",
            old_name="fee_feestru_tenant__e8bd84_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentattempt",
            new_name="fee_payment_tenant__bd8b32_idx",
            old_name="fee_payment_tenant__09de64_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentgatewayconfig",
            new_name="fee_payment_tenant__6ec883_idx",
            old_name="fee_payment_tenant__574426_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentinstallment",
            new_name="fee_payment_tenant__88bf4b_idx",
            old_name="fee_payment_tenant__32f71a_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentplan",
            new_name="fee_payment_tenant__4cd918_idx",
            old_name="fee_payment_tenant__a60b99_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentreminder",
            new_name="fee_payment_tenant__52806c_idx",
            old_name="fee_payment_tenant__837b6c_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentwebhook",
            new_name="fee_payment_tenant__47823c_idx",
            old_name="fee_payment_tenant__91fae2_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentwebhook",
            new_name="fee_payment_tenant__443eac_idx",
            old_name="fee_payment_tenant__26c56e_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdiscount",
            new_name="fee_student_tenant__bec6bd_idx",
            old_name="fee_student_tenant__b71528_idx",
        ),
        migrations.RenameIndex(
            model_name="studentfee",
            new_name="fee_student_tenant__980f5b_idx",
            old_name="fee_student_tenant__152285_idx",
        ),
        migrations.RenameIndex(
            model_name="studentfee",
            new_name="fee_student_tenant__d7db99_idx",
            old_name="fee_student_tenant__8bad4f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("tenant", "reference")},
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
