# Generated by Django 5.2.1 on 2026-02-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_curriculum_unique_together_and_more"),
        ("fee", "0003_add_fk_fields_to_fee_structure"),
        ("students", "0004_add_fk_fields_to_fee_structure"),
        ("tenants", "0003_add_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this fee applies to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="students.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="student_class",
            field=models.ForeignKey(
                help_text="Specific class this fee applies to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="students.class",
            ),
        ),
        migrations.AlterField(
            model_name="paymentinstallment",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installments",
                to="fee.payment",
            ),
        ),
        migrations.AlterField(
            model_name="paymentwebhook",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhooks",
                to="fee.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="feediscount",
            index=models.Index(
                fields=["tenant", "valid_from", "valid_to"],
                name="fee_fee_dis_tenant__178728_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["tenant", "student_class"],
                name="fee_fee_str_tenant__1d0991_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["tenant", "is_active"], name="fee_fee_str_tenant__2a06bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "receipt_number"],
                name="fee_payment_tenant__25ad33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "verified"], name="fee_payment_tenant__f0df86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentattempt",
            index=models.Index(
                fields=["tenant", "student_fee"], name="fee_payment_tenant__8afb28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentinstallment",
            index=models.Index(
                fields=["tenant", "due_date"], name="fee_payment_tenant__7d5260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentplan",
            index=models.Index(
                fields=["tenant", "student_fee"], name="fee_payment_tenant__7678dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreminder",
            index=models.Index(
                fields=["tenant", "student_fee"], name="fee_payment_tenant__21ce95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhook",
            index=models.Index(
                fields=["tenant", "event_id"], name="fee_payment_tenant__91076d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdiscount",
            index=models.Index(
                fields=["tenant", "is_active"], name="fee_student_tenant__cac6c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["tenant", "due_date"], name="fee_student_tenant__147133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["tenant", "is_overdue"], name="fee_student_tenant__3539de_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="feediscount",
            table="fee_fee_discount",
        ),
        migrations.AlterModelTable(
            name="feestructure",
            table="fee_fee_structure",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="fee_payment",
        ),
        migrations.AlterModelTable(
            name="paymentattempt",
            table="fee_payment_attempt",
        ),
        migrations.AlterModelTable(
            name="paymentgatewayconfig",
            table="fee_payment_gateway_config",
        ),
        migrations.AlterModelTable(
            name="paymentinstallment",
            table="fee_payment_installment",
        ),
        migrations.AlterModelTable(
            name="paymentplan",
            table="fee_payment_plan",
        ),
        migrations.AlterModelTable(
            name="paymentreminder",
            table="fee_payment_reminder",
        ),
        migrations.AlterModelTable(
            name="paymentwebhook",
            table="fee_payment_webhook",
        ),
        migrations.AlterModelTable(
            name="studentdiscount",
            table="fee_student_discount",
        ),
        migrations.AlterModelTable(
            name="studentfee",
            table="fee_student_fee",
        ),
    ]
