# Generated by Django 5.2.1 on 2026-02-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fee", "0004_add_fk_fields_to_fee_structure"),
    ]

    operations = []
