# Generated by Django 5.2.1 on 2026-03-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom",
            "0014_class_alter_classroom_options_alter_section_options_and_more",
        ),
        ("fee", "0005_migrate_fee_data_to_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="student_class",
            field=models.ForeignKey(
                help_text="Specific class this fee applies to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="classroom.class",
            ),
        ),
    ]
