# Generated by Django 5.2.1 on 2026-03-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
        ("fee", "0006_alter_feestructure_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this fee applies to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="academics.educationlevel",
            ),
        ),
    ]
