# Generated by Django 5.2.1 on 2026-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fee", "0007_alter_feestructure_education_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreminder",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="recipient",
            field=models.CharField(
                blank=True,
                help_text="The email address or phone number it went to.",
                max_length=254,
            ),
        ),
    ]
