# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_academiccalendar_event_type_and_more"),
        (
            "classroom",
            "0023_alter_class_education_level_alter_stream_grade_level_and_more",
        ),
        ("fee", "0008_payment_reminder_channel_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this fee applies to",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fee_structures",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="student_class",
            field=models.ForeignKey(
                help_text="Specific class this fee applies to",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fee_structures",
                to="classroom.class",
            ),
        ),
    ]
