# Generated by Django 5.2.1 on 2026-09-14 17:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0002_add_print_settings_to_exam"),
        ("students", "0011_alter_student_unique_together_and_more"),
        ("tenants", "0016_alter_platformcontent_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBTPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="No one can start after this. Anyone still writing finishes at this time, plus any extra time they are allowed.",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("include_objective", models.BooleanField(default=True)),
                (
                    "include_theory",
                    models.BooleanField(
                        default=False,
                        help_text="Theory and custom-section questions, answered by typing and marked by a teacher. Practical questions are never included.",
                    ),
                ),
                (
                    "objective_questions_per_attempt",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Give each student this many objective questions, drawn at random. Blank gives them all.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("shuffle_questions", models.BooleanField(default=True)),
                ("shuffle_options", models.BooleanField(default=True)),
                ("allow_backtracking", models.BooleanField(default=True)),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="If set, students must enter it to start.",
                        max_length=20,
                    ),
                ),
                (
                    "result_release",
                    models.CharField(
                        choices=[
                            ("on_submit", "As soon as the student submits"),
                            ("after_close", "When the exam window closes"),
                            ("manual", "When staff release them"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("results_released_at", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "sections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"key", "title", "instructions"}] in paper order',
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_paper",
                        to="exam.exam",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_paper",
            },
        ),
        migrations.CreateModel(
            name="CBTAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("submitted", "Submitted"),
                            ("timed_out", "Submitted when time ran out"),
                            ("voided", "Voided"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question_ids",
                    models.JSONField(
                        default=list,
                        help_text="The questions this student was given, in the order they see them",
                    ),
                ),
                (
                    "option_order",
                    models.JSONField(
                        default=dict,
                        help_text='{"<question id>": ["C", "A", "D", "B"]}',
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "objective_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "text_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="exam.examregistration",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cbt_attempts",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="cbt.cbtpaper",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_attempt",
                "ordering": ["started_at"],
            },
        ),
        migrations.CreateModel(
            name="CBTQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("objective", "Objective (choose one option)"),
                            ("text", "Typed answer (marked by a teacher)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Key of the paper section it belongs to",
                        max_length=40,
                    ),
                ),
                (
                    "source_number",
                    models.PositiveIntegerField(
                        help_text="Its number within that section of the exam"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position on the paper before any shuffling"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="HTML from the exam editor"),
                ),
                ("image_url", models.TextField(blank=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"key": "A", "text": "..."}]',
                    ),
                ),
                ("correct_option", models.CharField(blank=True, max_length=5)),
                (
                    "parts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sub-questions, as written on the exam",
                    ),
                ),
                ("table", models.JSONField(blank=True, null=True)),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="cbt.cbtpaper",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_question",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CBTAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.CharField(blank=True, max_length=5)),
                ("text_answer", models.TextField(blank=True)),
                (
                    "flagged",
                    models.BooleanField(
                        default=False, help_text="Marked by the student to come back to"
                    ),
                ),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                (
                    "marks_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="cbt.cbtattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="cbt.cbtquestion",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_answer",
            },
        ),
        migrations.CreateModel(
            name="CBTEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("resumed", "Resumed"),
                            ("device_changed", "Continued on a different device"),
                            ("focus_lost", "Left the exam window"),
                            ("focus_returned", "Came back to the exam window"),
                            ("fullscreen_exited", "Left full screen"),
                            ("copy_attempted", "Tried to copy"),
                            ("paste_attempted", "Tried to paste"),
                            ("connection_lost", "Lost connection"),
                            ("reconnected", "Reconnected"),
                            ("time_extended", "Given extra time"),
                            ("submitted", "Submitted"),
                            ("timed_out", "Submitted when time ran out"),
                            ("voided", "Voided"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "client_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the browser says it happened",
                        null=True,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who acted, for extensions and voids",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cbt.cbtattempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "cbt_event",
                "ordering": ["recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["attempt", "recorded_at"],
                        name="cbt_event_attempt_635829_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cbtpaper",
            index=models.Index(
                fields=["tenant", "status"], name="cbt_paper_tenant__d548bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cbtattempt",
            index=models.Index(
                fields=["tenant", "paper", "status"],
                name="cbt_attempt_tenant__46d3cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtattempt",
            constraint=models.UniqueConstraint(
                fields=("paper", "student", "number"), name="uq_cbt_attempt_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")),
                fields=("paper", "student"),
                name="uq_cbt_one_attempt_in_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtquestion",
            constraint=models.UniqueConstraint(
                fields=("paper", "order"), name="uq_cbt_question_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "text"),
                    models.Q(("correct_option", ""), _negated=True),
                    _connector="OR",
                ),
                name="chk_cbt_objective_has_answer",
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uq_cbt_answer_per_question"
            ),
        ),
    ]
