# Generated by Django 5.2.1 on 2026-09-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbtattempt",
            name="furthest_position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Furthest question the student has reached, counting from 0",
            ),
        ),
        migrations.AddField(
            model_name="cbtattempt",
            name="session_token_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 of the token the device sitting the attempt holds",
                max_length=64,
            ),
        ),
    ]
