# Generated by Django 5.2.1 on 2026-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0002_attempt_session_and_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbtevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("resumed", "Resumed"),
                    ("device_changed", "Continued on a different device"),
                    ("focus_lost", "Left the exam window"),
                    ("focus_returned", "Came back to the exam window"),
                    ("fullscreen_exited", "Left full screen"),
                    ("copy_attempted", "Tried to copy"),
                    ("paste_attempted", "Tried to paste"),
                    ("connection_lost", "Lost connection"),
                    ("reconnected", "Reconnected"),
                    ("time_extended", "Given extra time"),
                    ("reopened", "Let back in"),
                    ("submitted", "Submitted"),
                    ("timed_out", "Submitted when time ran out"),
                    ("voided", "Voided"),
                ],
                max_length=30,
            ),
        ),
    ]
