# Generated by Django 5.2.1 on 2026-09-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0004_marking_and_results"),
        ("exam", "0002_add_print_settings_to_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbtattempt",
            name="time_on_questions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Seconds the student\'s screen showed each question, as the exam page reports it: {"<question id>": seconds}',
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="bank_question",
            field=models.ForeignKey(
                blank=True,
                help_text="The question-bank question this came from, when it was drawn from the bank",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cbt_questions",
                to="exam.questionbank",
            ),
        ),
    ]
