# Generated by Django 5.2.1 on 2026-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0005_bank_link_and_question_time"),
        ("exam", "0002_add_print_settings_to_exam"),
        ("tenants", "0016_alter_platformcontent_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cbtquestion",
            name="chk_cbt_objective_has_answer",
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="numeric_answer",
            field=models.CharField(
                blank=True,
                help_text="For a numeric question, as the teacher wrote it",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="partial_credit",
            field=models.BooleanField(
                default=False,
                help_text="For choose all that apply: marks for part of the right choices, less wrong ones",
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="tolerance",
            field=models.DecimalField(
                decimal_places=8,
                default=0,
                help_text="How far either side of the numeric answer still counts",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Shown beside a numeric answer box, e.g. cm",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cbtanswer",
            name="selected_option",
            field=models.CharField(
                blank=True,
                help_text='The key chosen, or every key chosen in order for "choose all that apply": "AC"',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cbtanswer",
            name="text_answer",
            field=models.TextField(
                blank=True,
                help_text="A typed answer, or a number as the student wrote it",
            ),
        ),
        migrations.AlterField(
            model_name="cbtanswerkeychange",
            name="new_option",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cbtanswerkeychange",
            name="previous_option",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cbtquestion",
            name="correct_option",
            field=models.CharField(
                blank=True,
                help_text='The correct key, or every correct key in order for "choose all that apply": "AC"',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cbtquestion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("objective", "Objective (choose one option)"),
                    ("true_false", "True or false"),
                    ("multiple", "Choose all that apply"),
                    ("numeric", "Numeric answer"),
                    ("text", "Typed answer (marked by a teacher)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "text"),
                    models.Q(
                        ("kind", "numeric"),
                        models.Q(("numeric_answer", ""), _negated=True),
                    ),
                    models.Q(
                        ("kind__in", ["multiple", "objective", "true_false"]),
                        models.Q(("correct_option", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_cbt_question_has_answer",
            ),
        ),
    ]
