# Generated by Django 5.2.1 on 2026-09-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0006_question_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbtattempt",
            name="audio_plays",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Times the student has started each sound clip, as the exam page reports it: {"question:<id>" or "section:<key>": plays}',
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="audio",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='A sound clip to listen to: {"url", "title", "plays", "duration"}. plays 0 is as often as they like.',
            ),
        ),
        migrations.AlterField(
            model_name="cbtevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("resumed", "Resumed"),
                    ("device_changed", "Continued on a different device"),
                    ("focus_lost", "Left the exam window"),
                    ("focus_returned", "Came back to the exam window"),
                    ("fullscreen_exited", "Left full screen"),
                    ("copy_attempted", "Tried to copy"),
                    ("paste_attempted", "Tried to paste"),
                    ("connection_lost", "Lost connection"),
                    ("reconnected", "Reconnected"),
                    ("audio_played", "Played a sound clip"),
                    ("audio_failed", "A sound clip wouldn't play"),
                    ("time_extended", "Given extra time"),
                    ("reopened", "Let back in"),
                    ("submitted", "Submitted"),
                    ("timed_out", "Submitted when time ran out"),
                    ("voided", "Voided"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cbtpaper",
            name="sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"key", "title", "instructions", "audio"?}] in paper order',
            ),
        ),
    ]
