# Generated by Django 5.2.1 on 2026-09-15 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0007_sound_clips"),
        ("exam", "0004_sound_clips"),
        ("tenants", "0016_alter_platformcontent_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBTOfflinePackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Signs the attempts the station sends back",
                        max_length=64,
                    ),
                ),
                (
                    "question_ids",
                    models.JSONField(
                        default=list,
                        help_text="The paper's questions when the package was made",
                    ),
                ),
                (
                    "student_ids",
                    models.JSONField(
                        default=list, help_text="The students given a PIN"
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="The package file, as the station receives it"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cbt_offline_package",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="cbtquestion",
            name="chk_cbt_question_has_answer",
        ),
        migrations.AddField(
            model_name="cbtattempt",
            name="offline_id",
            field=models.UUIDField(
                blank=True,
                help_text="The station's id for the attempt, so an upload can be repeated",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="cbtquestion",
            name="key_withheld",
            field=models.BooleanField(
                default=False,
                help_text="A copy on an exam station, which is never given the answer key; marked in the cloud",
            ),
        ),
        migrations.AddConstraint(
            model_name="cbtquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "text"),
                    ("key_withheld", True),
                    models.Q(
                        ("kind", "numeric"),
                        models.Q(("numeric_answer", ""), _negated=True),
                    ),
                    models.Q(
                        ("kind__in", ["multiple", "objective", "true_false"]),
                        models.Q(("correct_option", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_cbt_question_has_answer",
            ),
        ),
        migrations.AddField(
            model_name="cbtofflinepackage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cbtofflinepackage",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offline_packages",
                to="cbt.cbtpaper",
            ),
        ),
        migrations.AddField(
            model_name="cbtofflinepackage",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cbtattempt",
            name="offline_package",
            field=models.ForeignKey(
                blank=True,
                help_text="The package this attempt was sat from, on the school's exam station",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="cbt.cbtofflinepackage",
            ),
        ),
    ]
