# Generated by Django 5.2.1 on 2026-10-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0008_offline_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="cbtpaper",
            name="auto_push_results",
            field=models.BooleanField(
                default=True,
                help_text="Write each student's score to their draft result as soon as their paper is fully marked",
            ),
        ),
    ]
