# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0009_score_columns_by_exam_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cbtanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="answers",
                to="cbt.cbtquestion",
            ),
        ),
        migrations.AlterField(
            model_name="cbtattempt",
            name="offline_package",
            field=models.ForeignKey(
                blank=True,
                help_text="The package this attempt was sat from, on the school's exam station",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attempts",
                to="cbt.cbtofflinepackage",
            ),
        ),
        migrations.AlterField(
            model_name="cbtattempt",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attempts",
                to="cbt.cbtpaper",
            ),
        ),
    ]
