# Generated by Django 5.2.1 on 2026-01-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_alter_classroom_unique_together_and_more'),
        ('subject', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # Step 1: Clear old unique_together constraints that reference school_id
        migrations.AlterUniqueTogether(
            name='schoolstreamconfiguration',
            unique_together=set(),
        ),
        # Step 2: Remove the old school_id field
        migrations.RemoveField(
            model_name='schoolstreamconfiguration',
            name='school_id',
        ),
        # Step 3: Add tenant fields to all models
        migrations.AddField(
            model_name='schoolstreamconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='schoolstreamsubjectassignment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        # Step 4: Update model options and unique_together with new tenant field
        migrations.AlterModelOptions(
            name='schoolstreamconfiguration',
            options={'ordering': ['tenant', 'stream', 'display_order'], 'verbose_name': 'School Stream Configuration', 'verbose_name_plural': 'School Stream Configurations'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolstreamconfiguration',
            unique_together={('tenant', 'stream', 'subject_role')},
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Subject code (e.g., MATH-NUR, ENG-PRI, PHY-SS)', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('tenant', 'code')},
        ),
    ]
