# Generated by Django 5.2.1 on 2026-02-27 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0013_add_new_category_and_type_models"),
        ("subject", "0002_add_tenant_fields"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["subject_order", "name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="credit_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Credit hours for this subject",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="grade_levels_old",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific grade levels where this subject is taught (OLD)",
                related_name="subjects",
                to="classroom.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="max_marks",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Maximum marks for this subject",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="passing_marks",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Minimum passing marks percentage",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="category",
            field=models.CharField(
                choices=[
                    ("core", "Core Subject"),
                    ("elective", "Elective Subject"),
                    ("cross_cutting", "Cross Cutting Subject"),
                    ("core_science", "Core Science"),
                    ("core_art", "Core Art"),
                    ("core_humanities", "Core Humanities"),
                    ("vocational", "Vocational/Pre-vocational"),
                    ("creative_arts", "Cultural & Creative Arts"),
                    ("religious", "Religious Studies"),
                    ("physical", "Physical & Health Education"),
                    ("language", "Language"),
                    ("practical", "Practical/Skills"),
                    ("nursery_activities", "Nursery Activities"),
                ],
                default="core",
                help_text="Subject category for organization (DEPRECATED - use category_new)",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="default_stream_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("core", "Core Subjects"),
                    ("elective", "Elective Subjects"),
                    ("cross_cutting", "Cross-Cutting Subjects"),
                ],
                help_text="Default role if not specifically configured by school",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="education_levels",
            field=models.JSONField(
                default=list,
                help_text="Education levels this subject applies to (DEPRECATED - use grade_levels)",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="grade_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grade levels where this subject is taught (new M2M field)",
                related_name="grade_subjects",
                to="classroom.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_cross_cutting",
            field=models.BooleanField(
                default=False,
                help_text="Whether this subject is cross-cutting across all streams",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="nursery_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Specific nursery levels (DEPRECATED)",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="ss_subject_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cross_cutting", "Cross Cutting"),
                    ("core_science", "Core Science"),
                    ("core_art", "Core Art"),
                    ("core_humanities", "Core Humanities"),
                    ("elective", "Elective"),
                ],
                help_text="Classification for Senior Secondary subjects (DEPRECATED - use subject_type_new)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SubjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Core Subject', 'Elective', 'Vocational')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this category (e.g., 'core', 'elective')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this category"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display (e.g., '#FF5733')",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying categories"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Category",
                "verbose_name_plural": "Subject Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject category (new FK field)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects_new",
                to="subject.subjectcategory",
            ),
        ),
        migrations.CreateModel(
            name="SubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type name (e.g., 'Cross Cutting', 'Core Science')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this type (e.g., 'cross_cutting', 'core_science')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this subject type"
                    ),
                ),
                (
                    "is_cross_cutting",
                    models.BooleanField(
                        default=False,
                        help_text="Whether subjects of this type apply to all streams",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying types"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Education levels where this type applies",
                        related_name="subject_types",
                        to="classroom.gradelevel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Type",
                "verbose_name_plural": "Subject Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_type_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject type classification (new FK field)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects_new",
                to="subject.subjecttype",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "code"], name="subject_sub_tenant__25fa98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["tenant", "is_active"], name="subject_sub_tenant__c12b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectcategory",
            index=models.Index(
                fields=["tenant", "code"], name="subject_sub_tenant__4cd78c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectcategory",
            index=models.Index(
                fields=["tenant", "is_active"], name="subject_sub_tenant__864db4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectcategory",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="subjecttype",
            index=models.Index(
                fields=["tenant", "code"], name="subject_sub_tenant__6a6f8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subjecttype",
            index=models.Index(
                fields=["tenant", "is_active"], name="subject_sub_tenant__481499_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjecttype",
            unique_together={("tenant", "code")},
        ),
    ]
