# Generated by Django 5.2.1 on 2026-04-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0020_alter_stream_stream_type"),
        ("subject", "0003_add_new_category_and_type_models"),
        ("tenants", "0003_add_settings_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Combination name (e.g., 'Government Combination', 'Science with Physics')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this combination (e.g., 'GOV-ARTS', 'PHY-SCI')",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this combination includes",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying combinations"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this combination is available for selection",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default combination for the stream",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "core_subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Core subjects in this combination",
                        related_name="core_combinations",
                        to="subject.subject",
                    ),
                ),
                (
                    "cross_cutting_subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cross-cutting subjects in this combination",
                        related_name="cross_cutting_combinations",
                        to="subject.subject",
                    ),
                ),
                (
                    "elective_subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Elective subjects in this combination",
                        related_name="elective_combinations",
                        to="subject.subject",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        help_text="Stream this combination belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_combinations",
                        to="classroom.stream",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Combination",
                "verbose_name_plural": "Subject Combinations",
                "ordering": ["tenant", "stream", "display_order", "name"],
                "unique_together": {("tenant", "stream", "code")},
            },
        ),
    ]
