# Generated by Django 5.2.1 on 2026-04-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0004_add_subject_combination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="grade_levels_old",
        ),
    ]
