# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_remove_grade_levels_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="category_new",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject category (new FK field)",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="subjects_new",
                to="subject.subjectcategory",
            ),
        ),
    ]
