# Generated by Django 5.2.1 on 2026-01-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
        ('students', '0002_resultchecktoken_and_more'),
        ('tenants', '0002_add_tenant_setup_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentstudentrelationship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='parentstudentrelationship',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelationship',
            unique_together={('tenant', 'parent', 'student')},
        ),
    ]
