# Generated by Django 5.2.1 on 2026-05-26 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0003_bulkuploadrecord"),
        ("students", "0010_alter_bulkuploadrecord_options_and_more"),
        ("tenants", "0009_add_teaching_model_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkuploadrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Parent Bulk Upload Record",
                "verbose_name_plural": "Parent Bulk Upload Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="parentprofile",
            unique_together={("tenant", "user")},
        ),
        migrations.AddConstraint(
            model_name="parentstudentrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_contact", True)),
                fields=("tenant", "student"),
                name="unique_primary_contact_per_student_per_tenant",
            ),
        ),
    ]
