# Generated by Django 5.2.1 on 2026-09-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0004_alter_bulkuploadrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentprofile",
            options={
                "ordering": ["user__first_name", "user__last_name", "id"],
                "verbose_name": "Parent Profile",
                "verbose_name_plural": "Parent Profiles",
            },
        ),
    ]
