# Generated by Django 5.2.1 on 2026-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("classroom", "0011_alter_classroomteacherassignment_classroom_and_more"),
        ("students", "0002_resultchecktoken_and_more"),
        ("teacher", "0003_teacher_signature_uploaded_at_teacher_signature_url"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="attendance__date_61f2e1_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["teacher", "date"], name="attendance__teacher_26db48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_76a8d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_3889e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["section", "date"], name="attendance__section_7dbe4c_idx"
            ),
        ),
    ]
