# Generated by Django 5.2.1 on 2026-01-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_attendance__date_61f2e1_idx_and_more'),
        ('classroom', '0012_alter_classroom_unique_together_and_more'),
        ('students', '0002_resultchecktoken_and_more'),
        ('tenants', '0002_add_tenant_setup_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('tenant', 'date', 'student', 'section')},
        ),
    ]
