# Generated by Django 5.2.1 on 2026-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0004_alter_attendance_unique_together_attendance_tenant_and_more",
        ),
        ("classroom", "0020_alter_stream_stream_type"),
        ("students", "0009_alter_bulkuploadrecord_uploaded_by"),
        ("teacher", "0005_bulkuploadrecord"),
        ("tenants", "0006_tenantsettings_animations_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__date_61f2e1_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__teacher_26db48_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__student_76a8d7_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__date_3889e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance__section_7dbe4c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(
                blank=True, help_text="Time when student arrived", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(
                blank=True, help_text="Time when student left", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "date"], name="attendance__tenant__3d37b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "teacher", "date"],
                name="attendance__tenant__08a49f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "student", "date"],
                name="attendance__tenant__685f40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "date", "status"],
                name="attendance__tenant__10c005_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "section", "date"],
                name="attendance__tenant__d5a13b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("tenant", "date", "student", "section"),
                name="unique_attendance_per_student_section_date",
            ),
        ),
    ]
