# Generated by Django 5.2.1 on 2026-06-02 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_remove_attendance_attendance__date_61f2e1_idx_and_more"),
        ("classroom", "0022_add_classroom_co_teacher"),
        ("students", "0011_alter_student_unique_together_and_more"),
        ("teacher", "0013_add_pd_approval_workflow"),
        ("tenants", "0009_add_teaching_model_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "session", "student"]},
        ),
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_attendance_per_student_section_date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="back_fill_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional note explaining why a historical record is being created. Shown in audit logs when marked_late=True.",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this record was first created in the system.",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_late",
            field=models.BooleanField(
                default=False,
                help_text="True when the record was created after the attendance date. Set automatically; used for compliance reporting.",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.CharField(
                choices=[("morning", "Morning"), ("afternoon", "Afternoon")],
                default="morning",
                help_text="Morning (start-of-day) or Afternoon (dismissal) session.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last modified."
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                help_text="The calendar date this record is for. May be in the past."
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="teacher.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(
                blank=True,
                help_text="Time student arrived (morning) or returned from break (afternoon).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.TimeField(
                blank=True,
                help_text="Time student left for break (morning) or dismissed (afternoon).",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "date", "session"],
                name="attendance__tenant__c1a36e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "student", "date", "session"],
                name="attendance__tenant__bf5823_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("tenant", "date", "student", "section", "session"),
                name="unique_attendance_per_student_section_date_session",
            ),
        ),
    ]
