# Generated by Django 5.2.1 on 2026-09-06 15:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_attendance_options_and_more"),
        ("students", "0011_alter_student_unique_together_and_more"),
        ("tenants", "0016_alter_platformcontent_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="attendance_settings",
                        serialize=False,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "morning_opens",
                    models.TimeField(
                        default=datetime.time(6, 30),
                        help_text="Earliest a tap counts as that day's arrival.",
                    ),
                ),
                (
                    "late_after",
                    models.TimeField(
                        default=datetime.time(8, 0),
                        help_text="An arrival at or after this time is marked Late, not Present.",
                    ),
                ),
                (
                    "afternoon_opens",
                    models.TimeField(
                        default=datetime.time(12, 0),
                        help_text="From this time, a tap belongs to the afternoon session.",
                    ),
                ),
                (
                    "dismissal_after",
                    models.TimeField(
                        default=datetime.time(14, 0),
                        help_text="Normal end of day. An exit before this is an early departure, which is what anomaly-only alerting notifies on.",
                    ),
                ),
                (
                    "duplicate_scan_window_seconds",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Re-reading the same tag in the same direction inside this many seconds is treated as one scan — no second record, no second alert.",
                    ),
                ),
                (
                    "alert_policy",
                    models.CharField(
                        choices=[
                            ("all_scans", "Notify on every scan"),
                            ("anomalies_only", "Notify only on unexpected scans"),
                        ],
                        default="all_scans",
                        help_text="Whether parents hear about every crossing or only unexpected ones. Drives the messaging bill as much as the provider does.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance Settings",
                "verbose_name_plural": "Attendance Settings",
            },
        ),
        migrations.CreateModel(
            name="StudentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="Tag's factory UID, normalized to uppercase hex.",
                        max_length=64,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional human note, e.g. 'blue rucksack'.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lost", "Lost"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True, default="")),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who enrolled this tag.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="GateScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="UID as scanned, normalized. Kept even if the tag is deleted.",
                        max_length=64,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Entry"), ("out", "Exit")],
                        help_text="Entry or exit. Sent explicitly by the scanner, never inferred.",
                        max_length=3,
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        help_text="When the device read the tag (may predate receipt if offline)."
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When the server accepted the scan.",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Caller-supplied device identifier, for auditing a disputed scan.",
                        max_length=100,
                    ),
                ),
                (
                    "client_scan_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client idempotency key; blank when the caller supplies none.",
                        max_length=64,
                    ),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False,
                        help_text="True when this landed inside the tenant's duplicate-scan window and so did not move attendance or notify anyone.",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        help_text="The daily summary row this scan was projected onto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_scans",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff account operating the scanner.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_scans_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_scans",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="attendance.studenttag",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="studenttag",
            index=models.Index(
                fields=["tenant", "uid", "status"],
                name="attendance__tenant__d5689b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studenttag",
            index=models.Index(
                fields=["tenant", "student", "status"],
                name="attendance__tenant__c46f42_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tenant", "uid"),
                name="unique_active_tag_uid_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="gatescan",
            index=models.Index(
                fields=["tenant", "uid", "scanned_at"],
                name="attendance__tenant__015cf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gatescan",
            index=models.Index(
                fields=["tenant", "student", "scanned_at"],
                name="attendance__tenant__d313fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gatescan",
            index=models.Index(
                fields=["tenant", "scanned_at"], name="attendance__tenant__de1f49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gatescan",
            index=models.Index(
                fields=["tenant", "direction", "scanned_at"],
                name="attendance__tenant__3c4d88_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="gatescan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_scan_id", ""), _negated=True),
                fields=("tenant", "client_scan_id"),
                name="unique_client_scan_id_per_tenant",
            ),
        ),
    ]
