# Generated by Django 5.2.1 on 2026-09-06 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancesettings_studenttag_gatescan_and_more"),
        ("parent", "0004_alter_bulkuploadrecord_options_and_more"),
        ("students", "0011_alter_student_unique_together_and_more"),
        ("tenants", "0016_alter_platformcontent_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentAlertPreference",
            fields=[
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="alert_preference",
                        serialize=False,
                        to="parent.parentprofile",
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in. Costs real money per message — see the alert policy.",
                    ),
                ),
                (
                    "muted",
                    models.BooleanField(
                        default=False,
                        help_text="Suppress every channel without losing the parent's choices.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parent Alert Preference",
                "verbose_name_plural": "Parent Alert Preferences",
            },
        ),
        migrations.CreateModel(
            name="ScanNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-app"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The address actually used — which number or inbox it went to.",
                        max_length=255,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which service carried it, e.g. brevo or twilio.",
                        max_length=30,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "queued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="In-app only: when the parent opened it.",
                        null=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="attendance.gatescan",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Denormalized from the scan for querying.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_notifications",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "queued_at"],
                        name="attendance__tenant__e018ce_idx",
                    ),
                    models.Index(
                        fields=["tenant", "recipient", "queued_at"],
                        name="attendance__tenant__b5b837_idx",
                    ),
                    models.Index(
                        fields=["tenant", "student", "queued_at"],
                        name="attendance__tenant__2d7f83_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "scan", "recipient", "channel"),
                        name="unique_scan_notification_per_recipient_channel",
                    )
                ],
            },
        ),
    ]
