# Generated by Django 5.2.1 on 2026-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_parentalertpreference_scannotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesettings",
            name="alert_policy",
            field=models.CharField(
                choices=[
                    ("all_scans", "Notify on every scan"),
                    ("anomalies_only", "Notify only on unexpected scans"),
                ],
                default="anomalies_only",
                help_text="Whether parents hear about every crossing or only unexpected ones. Drives the messaging bill as much as the provider does.",
                max_length=20,
            ),
        ),
    ]
