# Generated by Django 5.2.1 on 2026-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("user_created", "User Created"),
                    ("user_activated", "User Activated"),
                    ("user_deactivated", "User Deactivated"),
                    ("permission_change", "Permission Change"),
                    ("settings_update", "Settings Update"),
                    ("token_revoked", "Token Revoked"),
                    ("account_locked", "Account Locked"),
                    ("tag_enrolled", "Tag Enrolled"),
                    ("tag_revoked", "Tag Revoked"),
                    ("tag_reassigned", "Tag Reassigned"),
                ],
                max_length=50,
            ),
        ),
    ]
