# Generated by Django 5.2.1 on 2026-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teacher",
            "0002_rename_academic_year_teacherschedule_academic_session_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="signature_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="signature_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Digital Signature URL"
            ),
        ),
    ]
