# Generated by Django 5.2.1 on 2026-01-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_signature_uploaded_at_teacher_signature_url'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('tenant', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together={('tenant', 'teacher', 'day_of_week', 'start_time', 'end_time', 'academic_session', 'term')},
        ),
    ]
