# Generated by Django 5.2.1 on 2026-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_remove_grade_levels_old"),
        ("teacher", "0005_bulkuploadrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects this teacher is qualified/assigned to teach",
                related_name="teaching_teachers",
                to="subject.subject",
            ),
        ),
    ]
