# Generated by Django 5.2.1 on 2026-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
        ("teacher", "0006_add_subjects_to_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="education_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Education levels this teacher is assigned to. Leave blank to allow teaching across all levels. Schools can define their own levels in Academic Settings.",
                related_name="teachers",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
