# Generated by Django 5.2.1 on 2026-05-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0009_seed_default_activity_categories"),
        ("tenants", "0009_add_teaching_model_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppraisalCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=60)),
                ("description", models.TextField(blank=True)),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("all", "All Staff"),
                            ("teaching", "Teaching Staff Only"),
                            ("non-teaching", "Non-Teaching Staff Only"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum score for this criterion (usually 5 or 10).",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceAppraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appraiser_role",
                    models.CharField(
                        choices=[
                            ("proprietress", "Proprietress"),
                            ("head_teacher", "Head Teacher"),
                            ("form_teacher", "Form Teacher"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("first_term", "First Term"),
                            ("second_term", "Second Term"),
                            ("third_term", "Third Term"),
                            ("annual", "Annual Review"),
                            ("probation", "Probationary Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, help_text="e.g. 2025/2026", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "overall_comment",
                    models.TextField(
                        blank=True, help_text="General narrative from the appraiser."
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True,
                        help_text="Recommendations for improvement or recognition.",
                    ),
                ),
                (
                    "teacher_response",
                    models.TextField(
                        blank=True,
                        help_text="Teacher's written response to the appraisal.",
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appraiser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_appraisals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appraisals",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("commendation", "Commendation"),
                            ("appreciation", "Letter of Appreciation"),
                            ("query", "Query"),
                            ("warning", "Written Warning"),
                            ("caution", "Caution"),
                            ("improvement_plan", "Performance Improvement Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("punctuality", "Punctuality & Attendance"),
                            ("performance", "Teaching Performance"),
                            ("conduct", "Professional Conduct"),
                            ("innovation", "Innovation & Initiative"),
                            ("teamwork", "Teamwork & Collaboration"),
                            ("student_relations", "Student Relations"),
                            ("administrative", "Administrative Duties"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "teacher_comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional response from the teacher when acknowledging.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_staff_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_notes",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="Score given (1 to criteria.max_score)."
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="teacher.appraisalcriteria",
                    ),
                ),
                (
                    "appraisal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="teacher.performanceappraisal",
                    ),
                ),
            ],
            options={
                "unique_together": {("appraisal", "criteria")},
            },
        ),
    ]
