# Generated by Django 5.2.1 on 2026-05-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0011_seed_default_appraisal_criteria"),
        ("tenants", "0009_add_teaching_model_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the training, workshop, certification, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "dev_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("workshop", "Workshop"),
                            ("certification", "Certification"),
                            ("seminar", "Seminar"),
                            ("conference", "Conference"),
                            ("course", "Online / Self-Study Course"),
                            ("degree", "Academic Degree / Upgrade"),
                            ("other", "Other"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Awarding body, institution, or organiser.",
                        max_length=200,
                    ),
                ),
                (
                    "date_completed",
                    models.DateField(help_text="Date completed or attended."),
                ),
                (
                    "date_expires",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date (certifications only).",
                        null=True,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Number of CPD / contact hours.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to a certificate image or PDF.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Skills gained, key takeaways, or any extra notes.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Admin has verified this record is genuine.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_developments",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this record belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_pd_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_completed", "-created_at"],
            },
        ),
    ]
