# Generated by Django 5.2.1 on 2026-09-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0013_add_pd_approval_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["user__first_name", "user__last_name", "id"]},
        ),
    ]
