# Generated by Django 5.2.1 on 2026-10-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0014_list_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appraisalscore",
            name="criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="scores",
                to="teacher.appraisalcriteria",
            ),
        ),
        migrations.AlterField(
            model_name="staffactivitylog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="logs",
                to="teacher.staffactivitycategory",
            ),
        ),
    ]
