# Generated by Django 5.2.1 on 2026-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0002_sync_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="allowed_grade_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Specific grade levels this user can access. If empty, user can access all grades in assigned sections.",
                null=True,
            ),
        ),
    ]
