# Generated by Django 5.2.1 on 2026-04-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0003_userrole_allowed_grade_levels"),
        ("tenants", "0006_tenantsettings_animations_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communicationsettings",
            name="tenant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communication_settings",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="schoolannouncement",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="tenants.tenant",
            ),
        ),
    ]
