# Generated by Django 5.2.1 on 2026-04-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0004_communicationsettings_tenant_and_more"),
        ("tenants", "0006_tenantsettings_animations_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="When false the public landing page is not accessible.",
                    ),
                ),
                (
                    "hero_type",
                    models.CharField(
                        choices=[("static", "Static Image"), ("carousel", "Carousel")],
                        default="static",
                        max_length=10,
                    ),
                ),
                ("hero_image", models.URLField(blank=True, max_length=500, null=True)),
                ("hero_title", models.CharField(blank=True, max_length=200, null=True)),
                ("hero_subtitle", models.TextField(blank=True, null=True)),
                (
                    "hero_cta_text",
                    models.CharField(default="Enter Portal", max_length=80),
                ),
                ("hero_cta_url", models.CharField(default="/login", max_length=200)),
                (
                    "hero_secondary_cta_text",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "hero_secondary_cta_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("footer_text", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_page",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Landing Page",
                "verbose_name_plural": "Tenant Landing Pages",
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(max_length=300)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Page"),
                            ("section", "Page Section"),
                            ("external", "External URL"),
                        ],
                        default="internal",
                        max_length=10,
                    ),
                ),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_links",
                        to="schoolSettings.tenantlandingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Link",
                "verbose_name_plural": "Navigation Links",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="LandingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("about", "About"),
                            ("admissions", "Admissions"),
                            ("contact", "Contact"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Rich text / markdown content", null=True
                    ),
                ),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("contact_address", models.TextField(blank=True, null=True)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_hours",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_map_embed",
                    models.TextField(
                        blank=True, help_text="Google Maps embed URL", null=True
                    ),
                ),
                ("admissions_deadline", models.DateField(blank=True, null=True)),
                (
                    "admissions_fee",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "admissions_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "admissions_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "admissions_contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="schoolSettings.tenantlandingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Section",
                "verbose_name_plural": "Landing Sections",
                "ordering": ["display_order"],
            },
        ),
    ]
