# Generated by Django 5.2.1 on 2026-04-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0008_landing_carousel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_1_label",
            field=models.CharField(default="Students", max_length=80),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_1_value",
            field=models.CharField(default="1,000+", max_length=40),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_2_label",
            field=models.CharField(default="Teachers", max_length=80),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_2_value",
            field=models.CharField(default="80+", max_length=40),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_3_label",
            field=models.CharField(default="Programmes", max_length=80),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_3_value",
            field=models.CharField(default="20+", max_length=40),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_4_label",
            field=models.CharField(default="Years of Excellence", max_length=80),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stat_4_value",
            field=models.CharField(default="15+", max_length=40),
        ),
        migrations.AddField(
            model_name="tenantlandingpage",
            name="stats_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="landingsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("about", "About"),
                    ("admissions", "Admissions"),
                    ("contact", "Contact"),
                    ("school_activities", "School Activities"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
