# Generated by Django 5.2.1 on 2026-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0009_add_stats_and_school_activities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingsection",
            name="contact_phone",
            field=models.TextField(
                blank=True,
                help_text="One phone number per line — supports multiple numbers",
                null=True,
            ),
        ),
    ]
