# Generated by Django 5.2.1 on 2026-05-07 10:15

import schoolSettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0010_contact_phone_to_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingsection",
            name="contact_map_embed",
            field=models.TextField(
                blank=True,
                help_text="Google Maps embed URL (must start with https://www.google.com/maps/embed)",
                null=True,
                validators=[schoolSettings.models.validate_maps_embed_url],
            ),
        ),
    ]
