# Generated by Django 5.2.1 on 2026-09-24 18:07

import schoolSettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0011_alter_landingsection_contact_map_embed"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingsection",
            name="contact_streetview_embed",
            field=models.TextField(
                blank=True,
                help_text='Optional Street View of the school gate, shown under the map. Use a Google Maps embed URL. Either the one from Maps → Share → Embed a map (the src="..." value, starting https://www.google.com/maps/embed), or a https://maps.google.com/maps?q=...&output=embed link.',
                null=True,
                validators=[schoolSettings.models.validate_maps_embed_url],
            ),
        ),
        migrations.AlterField(
            model_name="landingsection",
            name="contact_map_embed",
            field=models.TextField(
                blank=True,
                help_text='Map of the school, shown on the contact section. Use a Google Maps embed URL. Either the one from Maps → Share → Embed a map (the src="..." value, starting https://www.google.com/maps/embed), or a https://maps.google.com/maps?q=...&output=embed link.',
                null=True,
                validators=[schoolSettings.models.validate_maps_embed_url],
            ),
        ),
    ]
