# Generated by Django 5.2.1 on 2026-09-30 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def school_from_creator(apps, schema_editor):
    """
    A role made before roles had a school belongs to its creator's school.
    Roles with no creator stay shared (tenant empty), as they were. Names were
    unique across the platform until now, so no school ends up with two.
    """
    Role = apps.get_model("schoolSettings", "Role")
    for role in Role.objects.filter(tenant__isnull=True, created_by__tenant__isnull=False):
        role.tenant_id = role.created_by.tenant_id
        role.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("schoolSettings", "0012_landingsection_contact_streetview_embed_and_more"),
        ("tenants", "0022_arrival_needs_gate_tracker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tenants.tenant",
            ),
        ),
        migrations.RunPython(school_from_creator, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="role_name_unique_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("name",),
                name="role_name_unique_among_shared",
            ),
        ),
    ]
