# Generated by Django 5.2.1 on 2026-04-06 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_educationlevel_is_system_default_and_more"),
        ("classroom", "0019_alter_class_grade_level"),
        ("student_promotions", "0001_initial"),
        ("students", "0008_student_lga_of_origin_student_lga_of_residence_and_more"),
        ("tenants", "0003_add_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="promotionrule",
            name="unique_promotion_rule_per_level",
        ),
        migrations.RemoveConstraint(
            model_name="studentpromotion",
            name="unique_student_promotion_per_session",
        ),
        migrations.RenameIndex(
            model_name="promotionrule",
            new_name="promotion_r_tenant__fdd7b8_idx",
            old_name="promo_rule_tenant_level_idx",
        ),
        migrations.RenameIndex(
            model_name="studentpromotion",
            new_name="student_pro_tenant__8c0e6e_idx",
            old_name="promo_tenant_session_idx",
        ),
        migrations.RenameIndex(
            model_name="studentpromotion",
            new_name="student_pro_tenant__e1b5e0_idx",
            old_name="promo_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="studentpromotion",
            new_name="student_pro_tenant__3f16d1_idx",
            old_name="promo_tenant_class_idx",
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="education_level",
            field=models.ForeignKey(
                help_text="Education level this rule applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_rules",
                to="academics.educationlevel",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="pass_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("49.00"),
                help_text="Minimum session average (%) required for auto-student_promotions",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="require_all_three_terms",
            field=models.BooleanField(
                default=True,
                help_text="If True, auto-student_promotions only runs when results for all three terms exist.  If False, available terms are averaged.",
            ),
        ),
        migrations.AlterField(
            model_name="promotionrule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="pass_threshold_applied",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Threshold that was in effect when auto-student_promotions ran",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Required for MANUAL overrides and HELD_BACK decisions",
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="session_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mean of available term averages",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Class the student was in during this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_promotions",
                to="classroom.class",
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Tenant this record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="term1_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average % from first-term report",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="term2_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average % from second-term report",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="term3_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average % from third-term report",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpromotion",
            name="terms_counted",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of terms included in session_average"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionrule",
            unique_together={("tenant", "education_level")},
        ),
        migrations.AlterUniqueTogether(
            name="studentpromotion",
            unique_together={("tenant", "student", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="promotionrule",
            index=models.Index(
                fields=["tenant", "is_active"], name="promotion_r_tenant__6b02ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentpromotion",
            index=models.Index(
                fields=["tenant", "student"], name="student_pro_tenant__9719ef_idx"
            ),
        ),
    ]
