# Generated by Django 5.2.1 on 2026-09-13 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0022_add_classroom_co_teacher"),
        (
            "student_promotions",
            "0002_remove_promotionrule_unique_promotion_rule_per_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpromotion",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentpromotion",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentpromotion",
            name="promoted_to_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Class the student was moved into when this promotion was applied",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_promotions",
                to="classroom.class",
            ),
        ),
    ]
