# Generated by Django 5.2.1 on 2026-09-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_promotions", "0003_student_promotion_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpromotion",
            name="graduated",
            field=models.BooleanField(
                default=False,
                help_text="Applied in the school's final class: the student left rather than moving up",
            ),
        ),
    ]
