# Generated by Django 5.2.1 on 2026-01-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_change_school_to_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_tenant__29ab49_idx',
            old_name='users_custo_tenant__role_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_tenant__44140a_idx',
            old_name='users_custo_tenant__sect_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='users_custo_tenant__bcd0ab_idx',
            old_name='users_custo_tenant__actv_idx',
        ),
    ]
