# Generated by Django 5.2.1 on 2026-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0008_rename_users_custo_tenant__role_idx_users_custo_tenant__29ab49_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True
            ),
        ),
    ]
