# Generated by Django 5.2.1 on 2026-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="supabase_id",
            field=models.UUIDField(
                blank=True, help_text="Supabase auth.users UUID", null=True, unique=True
            ),
        ),
    ]
