# Generated by Django 5.2.1 on 2026-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_supabase_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_version",
            field=models.IntegerField(
                default=0, help_text="Increment to invalidate all existing tokens"
            ),
        ),
    ]
