# Generated by hand to match Django's migration format (no local Django
# environment available to run makemigrations in this session).
# Adds "platform_admin" and "marketer" to CustomUser.role's choices.
# This is metadata-only for a plain CharField - Django does not enforce
# `choices` as a database constraint, so this does not alter the schema.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_token_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("platform_admin", "Platform Admin"),
                    ("marketer", "Marketer"),
                    ("secondary_admin", "Secondary Admin"),
                    ("senior_secondary_admin", "Senior Secondary Admin"),
                    ("junior_secondary_admin", "Junior Secondary Admin"),
                    ("primary_admin", "Primary Admin"),
                    ("nursery_admin", "Nursery Admin"),
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                max_length=30,
            ),
        ),
    ]
