# Generated by hand to match Django's migration format (no local Django
# environment available to run makemigrations in this session).
# Adds CustomUser.referral_code (used for a marketer's affiliate link) and
# backfills a code for any marketer account created before this field
# existed. New marketer accounts get a code assigned automatically by
# CustomUser.save() - see users/models.py.

from django.db import migrations, models

# Duplicated from users/models.py: migrations use a frozen historical model
# that doesn't carry the app's own save()/method overrides, so the code
# generation logic has to be self-contained here too.
_REFERRAL_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"


def _generate_code():
    import secrets

    return "".join(secrets.choice(_REFERRAL_CODE_ALPHABET) for _ in range(8))


def backfill_referral_codes(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    existing_codes = set(
        CustomUser.objects.exclude(referral_code=None).values_list(
            "referral_code", flat=True
        )
    )
    for user in CustomUser.objects.filter(role="marketer", referral_code=None):
        code = _generate_code()
        while code in existing_codes:
            code = _generate_code()
        existing_codes.add(code)
        user.referral_code = code
        user.save(update_fields=["referral_code"])


def noop_reverse(apps, schema_editor):
    # Nothing to undo - leaving referral codes in place on rollback is safe.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_customuser_role_platform_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True, max_length=12, null=True, unique=True, db_index=True
            ),
        ),
        migrations.RunPython(backfill_referral_codes, noop_reverse),
    ]
